export type NavLink = { label: string; href: string };
export type NavGroup = { label: string; href: string; items: NavLink[] };

export const en = {
  meta: {
    title: "NUUK — Financial AI Infrastructure",
    description:
      "AI-engineered quantitative trading and execution infrastructure for institutions and professional investors. FX, commodities, indices, equities and digital assets across 50+ venues.",
  },
  brand: {
    name: "NUUK",
    legalName: "NUUK Quant",
    email: "info@nuukquant.com",
    phone: "+971 58 688 4464",
    phoneHref: "tel:+971586884464",
    office: "Dubai International Financial Centre (DIFC), Dubai, UAE",
  },
  ui: {
    contact: "Contact",
    getStarted: "Get Started",
    contactUs: "Contact Us",
    learnMore: "Learn More",
    language: "Language",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    home: "NUUK home",
    noPosts: "No posts in this category yet.",
    riskDisclosure: "Risk disclosure",
  },
  nav: [
    {
      label: "Clients",
      href: "/clients/",
      items: [
        { label: "Banks", href: "/clients/banks/" },
        { label: "Brokerages", href: "/clients/brokerages/" },
        { label: "Asset Managers", href: "/clients/asset-managers/" },
        { label: "Family Offices", href: "/clients/family-offices/" },
        { label: "Professional Traders", href: "/clients/professional-traders/" },
        { label: "Individual Investors", href: "/clients/individual-investors/" },
      ],
    },
    {
      label: "Markets",
      href: "/markets/",
      items: [
        { label: "All Markets", href: "/markets/" },
        { label: "Foreign Exchange", href: "/markets/#fx" },
        { label: "Commodities", href: "/markets/#commodities" },
        { label: "Equity Indices", href: "/markets/#indices" },
        { label: "Equities & ETFs", href: "/markets/#equities" },
        { label: "Fixed Income", href: "/markets/#bonds" },
        { label: "Metals", href: "/markets/#metals" },
        { label: "Digital Assets", href: "/markets/#crypto" },
        { label: "Fee Structure", href: "/markets/pricing-overview/" },
      ],
    },
    {
      label: "Technology",
      href: "/technology/",
      items: [
        { label: "Platform", href: "/technology/" },
        { label: "API Integration", href: "/technology/#api" },
        { label: "AI Intelligence", href: "/technology/#ai" },
        { label: "Infrastructure", href: "/technology/#infrastructure" },
      ],
    },
    {
      label: "Insights",
      href: "/#insights",
      items: [
        { label: "Market Insights", href: "/#insights" },
        { label: "Press", href: "/#insights" },
        { label: "Events", href: "/#insights" },
      ],
    },
    {
      label: "About Us",
      href: "/company/",
      items: [
        { label: "Our Story", href: "/company/" },
        { label: "Contact Us", href: "/contact-us/" },
        { label: "Careers", href: "mailto:info@nuukquant.com?subject=Careers" },
      ],
    },
  ] as NavGroup[],
  legalLinks: [
    { label: "Risk Disclosure", href: "#risk" },
    { label: "Privacy", href: "#" },
    { label: "Terms of Use", href: "#" },
    { label: "Cookies", href: "#" },
    { label: "Fee Structure", href: "/markets/pricing-overview/" },
  ] as NavLink[],
  socials: [
    { label: "LinkedIn", href: "#", icon: "in" },
    { label: "X", href: "#", icon: "x" },
    { label: "YouTube", href: "#", icon: "yt" },
    { label: "Instagram", href: "#", icon: "ig" },
  ],
  home: {
    hero: {
      title: ["Precision.", "Intelligence.", "Execution."],
      kicker: "AI-ENGINEERED TRADING INFRASTRUCTURE",
      body:
        "NUUK is an AI-engineered quantitative trading company operating in global financial markets. We build proprietary algorithms, machine-learning models and institutional execution systems for disciplined, risk-controlled trading across FX, commodities, indices, equities and digital assets.",
      cta: { label: "Contact Us", href: "/contact-us/" },
    },
    audiences: [
      { label: "Banks", href: "/clients/banks/" },
      { label: "Brokerages", href: "/clients/brokerages/" },
      { label: "Asset Managers", href: "/clients/asset-managers/" },
      { label: "Family Offices", href: "/clients/family-offices/" },
      { label: "Professional Traders", href: "/clients/professional-traders/" },
      { label: "Individual Investors", href: "/clients/individual-investors/" },
    ],
    core: [
      {
        title: ["Multi-Asset", "Coverage"],
        body: "FX, commodities, equity indices, equities, fixed income, metals and digital assets, reached through a diversified network of regulated venues and liquidity providers.",
        href: "/markets/",
        icon: "diversification",
      },
      {
        title: ["Proprietary", "Technology"],
        body: "Custom-built machine-learning models, ultra-low-latency execution and a web platform with FIX and HTTP API access.",
        href: "/technology/",
        icon: "technology",
      },
      {
        title: ["Transparent", "Fee Structure"],
        body: "Clear execution, financing and data charges agreed up front. No hidden mark-ups.",
        href: "/markets/pricing-overview/",
        icon: "pricing",
      },
      {
        title: ["Institutional", "Service"],
        body: "A dedicated relationship manager backed by our execution desk, risk team and engineers.",
        href: "/contact-us/",
        icon: "service",
      },
    ],
    servicing: {
      title: "One Team Serving Institutions and Professional Investors Worldwide",
      items: [
        "Structured onboarding with access to the platform and API tools from day one",
        "Coverage across time zones from our base in DIFC, Dubai",
        "Execution desk support for block, OTC and multi-venue orders",
        "Post-trade reporting, reconciliation and risk analytics",
      ],
      cta: { label: "Get Started", href: "/contact-us/" },
    },
    network: {
      title: "Our Network",
      partners: [
        "Tier-1 FX ECNs",
        "Global Futures Exchanges",
        "Equity Index Venues",
        "Digital Asset Venues",
        "Prime Custodians",
        "Liquidity Providers",
      ],
    },
    experts: {
      title: "Proprietary Trading Platform",
      items: [
        {
          title: "Built by Engineers",
          body: "A web platform and execution engine designed in-house, delivered through a single multi-currency account.",
        },
        {
          title: "Customisation and Integrations",
          body: "FIX and HTTP APIs, tailored instrument sets and white-label deployments for partners who need their own front end.",
        },
        {
          title: "Distributed Infrastructure",
          body: "Co-located, redundant infrastructure across the major trading hubs with sub-millisecond internal latency.",
        },
      ],
      cta: { label: "Learn More", href: "/technology/" },
      imageAlt: "NUUK trading platform on desktop, laptop and phone",
    },
    exchanges: {
      title: "Global Venue Coverage",
      groups: [
        [
          { city: "New York, United States", codes: ["NYSE", "NASDAQ"] },
          { city: "Chicago, United States", codes: ["CME", "CBOT", "CBOE"] },
          { city: "Atlanta, United States", codes: ["ICE"] },
        ],
        [
          { city: "London, United Kingdom", codes: ["LSE", "ICE Futures Europe"] },
          { city: "Frankfurt, Germany", codes: ["Eurex", "Xetra"] },
          { city: "Zurich, Switzerland", codes: ["SIX"] },
        ],
        [
          { city: "Dubai, UAE", codes: ["DGCX", "DFM"] },
          { city: "Abu Dhabi, UAE", codes: ["ADX"] },
        ],
        [
          { city: "Hong Kong", codes: ["HKEX"] },
          { city: "Singapore", codes: ["SGX"] },
          { city: "Tokyo, Japan", codes: ["JPX"] },
        ],
      ],
    },
    broker: {
      title: "Built on Governance",
      body:
        "Our infrastructure connects to a diversified network of regulated venues, custodians and liquidity providers, enabling automated, multi-venue execution with data integrity, latency efficiency and complete systematic governance.",
      cta: { label: "About NUUK", href: "/company/" },
      items: [
        { title: "Systematic Governance", body: "Every decision is rule-based, logged and auditable." },
        { title: "Trusted Counterparties", body: "Regulated venues and established liquidity providers only." },
        { title: "Secure Custody", body: "Client assets held with established custodians." },
        { title: "Segregated Assets", body: "Client assets kept separate from company funds." },
      ],
    },
    pulse: {
      title: "NUUK Insights",
      tabs: ["All Posts", "Insights", "Press", "Events"],
      posts: [
        {
          title: "Rates, growth and the dollar into year-end",
          excerpt: "What our macro models are pricing across FX and rates as the policy path is repriced.",
          tag: "Insight",
          category: "Insights",
          date: "Sep 4, 2026",
          tone: "stocks",
        },
        {
          title: "Gold near record highs: what the signal engine sees",
          excerpt: "Metals stay bid while real yields soften. A look at our momentum and mean-reversion signals.",
          tag: "Insight",
          category: "Insights",
          date: "Sep 3, 2026",
          tone: "metals",
        },
        {
          title: "NUUK expands multi-venue connectivity",
          excerpt: "New direct connections add depth across FX, futures and digital asset venues.",
          tag: "Press",
          category: "Press",
          date: "Sep 2, 2026",
          tone: "currencies",
        },
        {
          title: "Institutional roundtables at DIFC this autumn",
          excerpt: "Join our team for a series of closed-door sessions on AI in execution and risk.",
          tag: "Event",
          category: "Events",
          date: "Sep 1, 2026",
          tone: "crypto",
        },
      ],
    },
  },
  audiences: {
    banks: {
      title: "Banks",
      intro:
        "Execution, connectivity and AI-driven analytics for banks that need multi-asset market access through a single, disciplined counterparty.",
      highlights: [
        { title: "Direct API", body: "FIX and HTTP connectivity for order routing, market data and reporting." },
        { title: "White Label", body: "Deploy our platform under your brand with tailored instruments and permissions." },
        { title: "Dedicated Support", body: "Execution desk and post-trade teams in your time zone." },
      ],
    },
    brokerages: {
      title: "Brokerages",
      intro: "Extend your product range with multi-asset coverage, competitive execution and a scalable back office.",
      highlights: [
        { title: "Omnibus & Sub-Accounts", body: "Flexible account structures for end-client setups." },
        { title: "White Label", body: "A ready-made trading front end that carries your brand." },
        { title: "Dedicated Support", body: "Onboarding, execution desk and reconciliation support." },
      ],
    },
    "asset-managers": {
      title: "Asset Managers",
      intro: "Execute across global venues from one multi-currency account with institutional reporting and custody.",
      highlights: [
        { title: "Multi-Asset Execution", body: "FX, commodities, indices, equities, fixed income, metals and digital assets." },
        { title: "Portfolio Dashboards", body: "Real-time risk, exposure and P&L analytics." },
        { title: "Dedicated Support", body: "A relationship manager backed by our execution desk." },
      ],
    },
    "family-offices": {
      title: "Family Offices",
      intro: "Discreet, personalised service with global diversification and secure custody.",
      highlights: [
        { title: "Global Diversification", body: "Access to exchange-traded and OTC markets worldwide." },
        { title: "Secure Custody", body: "Segregated assets with established custodians." },
        { title: "Dedicated Support", body: "A single point of contact for every request." },
      ],
    },
    "professional-traders": {
      title: "Professional Traders",
      intro: "Low-latency execution, live market depth and algorithmic tools built by engineers who trade.",
      highlights: [
        { title: "Live Market Depth", body: "Full order-book transparency across venues." },
        { title: "Algorithmic Execution", body: "Automate entries and exits with rule-based orders." },
        { title: "Risk Controls", body: "Position sizing, circuit breakers and real-time exposure limits." },
      ],
    },
    "individual-investors": {
      title: "Individual Investors",
      intro: "Access new asset classes through one account and a platform that grows with you.",
      highlights: [
        { title: "New Asset Classes", body: "Equities, indices, metals and digital assets from one account." },
        { title: "Transparent Fees", body: "Clear execution and financing charges, agreed up front." },
        { title: "Dedicated Support", body: "Human support when you need it." },
      ],
    },
  },
  assetClasses: [
    { id: "fx", label: "Foreign Exchange", tone: "currencies", body: "Spot FX majors, minors and exotics with Tier-1 ECN liquidity." },
    { id: "commodities", label: "Commodities", tone: "futures", body: "Energy, agricultural and metals futures on major exchanges." },
    { id: "indices", label: "Equity Indices", tone: "options", body: "Global index futures and CFDs with deep liquidity." },
    { id: "equities", label: "Equities & ETFs", tone: "stocks", body: "Listed equities and ETFs across US, European and Asian venues." },
    { id: "bonds", label: "Fixed Income", tone: "bonds", body: "Government and corporate bonds, exchange-traded and OTC." },
    { id: "metals", label: "Metals", tone: "metals", body: "Gold, silver, platinum and palladium, spot and futures." },
    { id: "crypto", label: "Digital Assets", tone: "crypto", body: "Major digital assets via regulated venues, 24/7." },
  ],
  technologyFeatures: [
    { title: "Proprietary ML Models", body: "Adaptive learning systems trained on decades of market data." },
    { title: "Ultra-Low Latency Execution", body: "Co-located servers, direct market access and smart order routing." },
    { title: "Advanced Risk Management", body: "Automated position sizing, circuit breakers and stress testing." },
    { title: "Multi-Venue Connectivity", body: "Direct connections to 50+ regulated venues and liquidity providers." },
    { title: "Real-Time Data Aggregation", body: "Millions of market data points per second, normalised and validated." },
    { title: "Bank-Grade Security", body: "Encryption, multi-factor authentication and hardware security modules." },
    { title: "Portfolio Dashboards", body: "Real-time risk, exposure and P&L analytics." },
    { title: "White Label Solutions", body: "Your brand on our infrastructure, engineered for control." },
  ],
  rateCategories: [
    { title: "Execution Commissions", body: "Per-instrument commissions agreed in your fee schedule, disclosed before every trade." },
    { title: "Financing", body: "Overnight financing on leveraged positions, quoted per instrument and currency." },
    { title: "Borrow Costs", body: "Stock and asset borrow costs for short positions, disclosed before execution." },
    { title: "Data & Connectivity", body: "Market data and API connectivity at flat, published rates." },
    { title: "Custody & Settlement", body: "Custody, settlement and withdrawal charges listed in your schedule." },
    { title: "Inactivity", body: "Applied only after a prolonged period without activity." },
  ],
  pages: {
    ctaBand: {
      title: "Where capital meets machine intelligence.",
      body: "Talk to our team about onboarding, fees and integration.",
      cta: { label: "Contact Us", href: "/contact-us/" },
    },
    clients: {
      metaTitle: "Clients: Institutions, Family Offices & Traders",
      metaDescription: "Why banks, brokerages, asset managers, family offices and professional traders choose NUUK.",
      kicker: "Clients",
      title: "Our clients",
      intro: "From banks to individual investors, NUUK provides one platform, one account and one point of contact.",
      whyTitle: "Why professionals choose NUUK",
      reasons: [
        { title: "Institutional discipline", body: "Systematic governance across execution, risk and reporting." },
        { title: "Trusted by professionals", body: "Built for institutions and professional investors, from DIFC to the world." },
        { title: "Access across 50+ venues", body: "One multi-currency account, all major asset classes." },
        { title: "Institutional technology", body: "Proprietary platform, FIX/HTTP APIs and AI-driven analytics." },
        { title: "Always available", body: "A global team and execution desk in your time zone." },
      ],
      whoTitle: "Who we serve",
      ctaTitle: "Start the right conversation",
    },
    audience: {
      kicker: "Clients",
      supportTitle: "Dedicated Support",
      supportBody: "A relationship manager, execution desk and engineering team in your time zone.",
    },
    markets: {
      metaTitle: "Markets: Multi-Asset Coverage Across 50+ Venues",
      metaDescription: "FX, commodities, equity indices, equities, fixed income, metals and digital assets from one multi-currency account.",
      kicker: "Markets",
      title: "Markets",
      intro: "Trade the world's most liquid markets from a single, multi-currency account.",
      cta: { label: "Get Started", href: "/contact-us/" },
      kpis: [
        ["50+", "regulated venues"],
        ["150+", "active AI models"],
        ["<5ms", "average execution latency"],
      ],
      assetsTitle: "Asset Classes",
      features: [
        { title: "Global Venue Access", body: "One account for venues in the Americas, Europe, the Middle East and Asia." },
        { title: "Safe Asset Custody", body: "Segregated client assets with established custodians." },
        { title: "Cross-Margining", body: "Portfolio-level margin across asset classes." },
        { title: "Proprietary Technology", body: "Web platform, FIX/HTTP API and AI-driven analytics." },
      ],
      depositsTitle: "Multi-Currency Deposits",
      depositsBody:
        "Fund your account in USD, EUR, GBP, AED and other major currencies. Hold balances in multiple currencies simultaneously and settle trades without forced conversion.",
    },
    pricing: {
      metaTitle: "Fee Structure",
      metaDescription: "Clear execution, financing, data and custody charges, agreed up front.",
      kicker: "Markets",
      title: "Fee Structure",
      intro: "Clear execution, financing, data and custody charges, agreed up front. No hidden mark-ups.",
      cta: { label: "Request a Schedule", href: "/contact-us/" },
      assetsTitle: "Asset Classes",
      assetNote: "Commission and financing: per your fee schedule",
      ratesTitle: "What You Pay For",
      ctaTitle: "Request your fee schedule",
      ctaBody: "Institutional and professional clients receive a tailored schedule before onboarding.",
    },
    technology: {
      metaTitle: "Trading Technology: Platform, APIs & AI",
      metaDescription: "Proprietary web platform, FIX and HTTP APIs, white label and AI-driven market intelligence.",
      kicker: "Technology",
      title: "Proprietary Technology",
      intro: "Enterprise-grade systems engineered for speed, reliability and performance: machine learning, low-latency execution and risk control in one stack.",
      cta: { label: "Request Demo", href: "/contact-us/" },
      stackTitle: "Advanced technology stack",
      httpTitle: "HTTP API",
      httpBody: "REST endpoints for market data, orders, positions and reporting. Ideal for portfolio tooling, dashboards and automated strategies. No minimum commitment required.",
      fixTitle: "FIX API",
      fixBody: "Low-latency FIX 4.4 sessions for order routing and drop-copy, co-located across global trading hubs for institutional execution quality.",
      aiTitle: "Next-generation AI intelligence",
      ai: [
        { title: "Deep Learning Networks", body: "Multi-layered neural networks trained on billions of data points, combining LSTM, transformer models and reinforcement learning." },
        { title: "Predictive Analytics Engine", body: "Forecasting models that analyse sentiment, order flow, volatility and macro indicators, continuously validated against real outcomes." },
        { title: "Risk Governance", body: "Real-time exposure limits, circuit breakers and stress tests guard capital around the clock." },
      ],
      infraTitle: "Global Trading Infrastructure",
      infraBody: "Direct connections to 50+ regulated venues and liquidity providers with redundant network architecture, real-time data aggregation and bank-grade security. White-label deployments available for partners.",
      infraCta: { label: "Talk to our engineers", href: "/contact-us/" },
    },
    company: {
      metaTitle: "About NUUK: AI-Engineered Trading Infrastructure",
      metaDescription: "NUUK is an AI-engineered quantitative trading and infrastructure company headquartered in DIFC, Dubai.",
      kicker: "About Us",
      title: "Our Story",
      intro: "NUUK is an AI-engineered quantitative trading and infrastructure company. We combine proprietary algorithms, institutional execution systems and a global venue network to give professionals disciplined access to world markets.",
      principlesTitle: "Guiding Principles",
      principles: [
        { title: "Discipline", body: "Every decision is systematic, risk-controlled and auditable." },
        { title: "Transparency", body: "Clear pricing, clear reporting and clear communication." },
        { title: "Engineering", body: "We build our own platforms, models and connectivity." },
        { title: "Partnership", body: "A relationship manager who knows your business." },
      ],
      deliverTitle: "You drive the change, we deliver",
      deliverBody: "Our infrastructure connects to a diversified network of regulated global venues and liquidity providers, enabling automated, multi-venue execution with data integrity, latency efficiency and complete systematic governance.",
      ctaTitle: "International team, local presence",
      ctaBody: "Headquartered in DIFC, Dubai, serving clients across time zones.",
    },
    contact: {
      metaTitle: "Contact Us",
      metaDescription: "Talk to our team about onboarding, fees and integration.",
      kicker: "About Us",
      title: "Contact Us",
      intro: "Customer support, account management and enquiries.",
      supportTitle: "Customer Support",
      managerTitle: "Talk to our team in Dubai",
      formTitle: "Suggestions & Enquiries",
      form: {
        name: "Name",
        namePlaceholder: "Your name",
        email: "Email",
        emailPlaceholder: "you@company.com",
        company: "Company (optional)",
        companyPlaceholder: "Company",
        message: "Message",
        messagePlaceholder: "How can we help?",
        submit: "Send enquiry",
        note: "This opens your email client with the message pre-filled. No data is stored on this site.",
        errorRequired: "Please fill in your name, email and message.",
        errorEmail: "Please enter a valid email address.",
        subject: "Enquiry from",
      },
      ctaBody: "Institutional and professional enquiries are answered within one business day.",
      ctaLabel: "Email us",
    },
    footer: {
      copyright: "All rights reserved.",
      legal1:
        "is an AI-engineered quantitative trading and trading-infrastructure company based in the Dubai International Financial Centre. Services are offered to professional and institutional clients; availability depends on your jurisdiction and applicable regulation.",
      legal2:
        "Any information on this website is provided for informational purposes only and does not constitute investment advice or an offer or solicitation to buy or sell any financial instrument or service.",
      risk1:
        "Trading involves substantial risk. Investing in FX, commodities, indices, equities, fixed income, metals and digital assets can result in losses that exceed your initial investment, and trading on margin carries additional risk. Past performance of any model, strategy or system is not a guarantee of future results. Make sure you understand these risks before engaging any service.",
      risk2: "Live market figures and system telemetry shown on this website are illustrative and may be delayed. Institutional enquiries only.",
      risk3: "Please verify that any communication claiming to come from NUUK originates from the nuukquant.com domain. Report suspected misuse of our name to",
    },
  },
};

export type SiteContent = typeof en;

export const toneBg: Record<string, string> = {
  stocks: "bg-stocks",
  currencies: "bg-currencies",
  futures: "bg-futures",
  options: "bg-options",
  metals: "bg-metals",
  bonds: "bg-bonds",
  crypto: "bg-crypto",
};
