import type { ContentOverride } from "@/i18n";

export const es: ContentOverride = {
  meta: {
    title: "NUUK — Infraestructura financiera con IA",
    description:
      "Infraestructura de trading cuantitativo y ejecución diseñada con IA para instituciones e inversores profesionales. Divisas, materias primas, índices, acciones y activos digitales en más de 50 mercados.",
  },
  brand: { office: "Dubai International Financial Centre (DIFC), Dubái, EAU" },
  ui: {
    contact: "Contacto",
    getStarted: "Empezar",
    contactUs: "Contáctenos",
    learnMore: "Más información",
    language: "Idioma",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
    home: "Inicio NUUK",
    noPosts: "Todavía no hay publicaciones en esta categoría.",
    riskDisclosure: "Advertencia de riesgo",
  },
  nav: [
    { label: "Clientes", items: [{ label: "Bancos" }, { label: "Brókers" }, { label: "Gestores de activos" }, { label: "Family offices" }, { label: "Traders profesionales" }, { label: "Inversores particulares" }] },
    { label: "Mercados", items: [{ label: "Todos los mercados" }, { label: "Divisas" }, { label: "Materias primas" }, { label: "Índices bursátiles" }, { label: "Acciones y ETF" }, { label: "Renta fija" }, { label: "Metales" }, { label: "Activos digitales" }, { label: "Estructura de comisiones" }] },
    { label: "Tecnología", items: [{ label: "Plataforma" }, { label: "Integración API" }, { label: "Inteligencia artificial" }, { label: "Infraestructura" }] },
    { label: "Análisis", items: [{ label: "Análisis de mercado" }, { label: "Prensa" }, { label: "Eventos" }] },
    { label: "Nosotros", items: [{ label: "Nuestra historia" }, { label: "Contáctenos" }, { label: "Empleo" }] },
  ],
  legalLinks: [{ label: "Advertencia de riesgo" }, { label: "Privacidad" }, { label: "Términos de uso" }, { label: "Cookies" }, { label: "Estructura de comisiones" }],
  home: {
    hero: {
      title: ["Precisión.", "Inteligencia.", "Ejecución."],
      kicker: "INFRAESTRUCTURA DE TRADING DISEÑADA CON IA",
      body: "NUUK es una empresa de trading cuantitativo diseñada con IA que opera en los mercados financieros globales. Desarrollamos algoritmos propios, modelos de aprendizaje automático y sistemas de ejecución institucionales para un trading disciplinado y con riesgo controlado en divisas, materias primas, índices, acciones y activos digitales.",
      cta: { label: "Contáctenos" },
    },
    audiences: [{ label: "Bancos" }, { label: "Brókers" }, { label: "Gestores de activos" }, { label: "Family offices" }, { label: "Traders profesionales" }, { label: "Inversores particulares" }],
    core: [
      { title: ["Cobertura", "multiactivo"], body: "Divisas, materias primas, índices, acciones, renta fija, metales y activos digitales a través de una red diversificada de mercados regulados y proveedores de liquidez." },
      { title: ["Tecnología", "propia"], body: "Modelos de aprendizaje automático desarrollados internamente, ejecución de latencia ultrabaja y plataforma web con acceso API FIX y HTTP." },
      { title: ["Estructura de comisiones", "transparente"], body: "Comisiones de ejecución, financiación y datos claras y acordadas de antemano. Sin márgenes ocultos." },
      { title: ["Servicio", "institucional"], body: "Un gestor de relación dedicado, respaldado por nuestra mesa de ejecución, el equipo de riesgo y los ingenieros." },
    ],
    servicing: {
      title: "Un solo equipo al servicio de instituciones e inversores profesionales en todo el mundo",
      items: ["Onboarding estructurado con acceso a la plataforma y a las herramientas API desde el primer día", "Cobertura de todas las zonas horarias desde nuestra sede en el DIFC, Dubái", "Soporte de la mesa de ejecución para órdenes en bloque, OTC y multimercado", "Informes post-trade, conciliación y análisis de riesgo"],
      cta: { label: "Empezar" },
    },
    network: { title: "Nuestra red", partners: ["ECN de divisas de primer nivel", "Bolsas mundiales de futuros", "Mercados de índices bursátiles", "Mercados de activos digitales", "Custodios prime", "Proveedores de liquidez"] },
    experts: {
      title: "Plataforma de trading propia",
      items: [
        { title: "Creada por ingenieros", body: "Una plataforma web y un motor de ejecución diseñados internamente, disponibles a través de una única cuenta multidivisa." },
        { title: "Personalización e integraciones", body: "API FIX y HTTP, conjuntos de instrumentos a medida y despliegues de marca blanca para socios que necesitan su propia interfaz." },
        { title: "Infraestructura distribuida", body: "Infraestructura colocalizada y redundante en los principales centros de trading con latencia interna inferior al milisegundo." },
      ],
      cta: { label: "Más información" },
      imageAlt: "Plataforma de trading NUUK en ordenador, portátil y móvil",
    },
    exchanges: {
      title: "Cobertura global de mercados",
      groups: [
        [{ city: "Nueva York, Estados Unidos" }, { city: "Chicago, Estados Unidos" }, { city: "Atlanta, Estados Unidos" }],
        [{ city: "Londres, Reino Unido" }, { city: "Fráncfort, Alemania" }, { city: "Zúrich, Suiza" }],
        [{ city: "Dubái, EAU" }, { city: "Abu Dabi, EAU" }],
        [{ city: "Hong Kong" }, { city: "Singapur" }, { city: "Tokio, Japón" }],
      ],
    },
    broker: {
      title: "Construido sobre la gobernanza",
      body: "Nuestra infraestructura se conecta a una red diversificada de mercados regulados, custodios y proveedores de liquidez, lo que permite una ejecución automatizada multimercado con integridad de datos, eficiencia de latencia y gobernanza sistemática completa.",
      cta: { label: "Sobre NUUK" },
      items: [
        { title: "Gobernanza sistemática", body: "Cada decisión se basa en reglas, queda registrada y es auditable." },
        { title: "Contrapartes de confianza", body: "Solo mercados regulados y proveedores de liquidez consolidados." },
        { title: "Custodia segura", body: "Activos de los clientes en custodios consolidados." },
        { title: "Activos segregados", body: "Activos de los clientes separados de los fondos de la empresa." },
      ],
    },
    pulse: {
      title: "Análisis NUUK",
      tabs: ["Todo", "Análisis", "Prensa", "Eventos"],
      posts: [
        { title: "Tipos, crecimiento y dólar hacia fin de año", excerpt: "Lo que descuentan nuestros modelos macro en divisas y tipos mientras se reevalúa la senda de política monetaria.", tag: "Análisis", date: "4 sept 2026" },
        { title: "El oro cerca de máximos: qué ve el motor de señales", excerpt: "Los metales siguen demandados mientras los rendimientos reales se relajan. Una mirada a nuestras señales de momentum y reversión a la media.", tag: "Análisis", date: "3 sept 2026" },
        { title: "NUUK amplía su conectividad multimercado", excerpt: "Nuevas conexiones directas añaden profundidad en divisas, futuros y activos digitales.", tag: "Prensa", date: "2 sept 2026" },
        { title: "Mesas redondas institucionales en el DIFC este otoño", excerpt: "Únase a nuestro equipo en una serie de sesiones a puerta cerrada sobre IA en ejecución y riesgo.", tag: "Evento", date: "1 sept 2026" },
      ],
    },
  },
  audiences: {
    banks: { title: "Bancos", intro: "Ejecución, conectividad y análisis impulsados por IA para bancos que necesitan acceso multiactivo a los mercados a través de una única contraparte disciplinada.", highlights: [{ title: "API directa", body: "Conectividad FIX y HTTP para enrutamiento de órdenes, datos de mercado e informes." }, { title: "Marca blanca", body: "Despliegue nuestra plataforma con su marca, con instrumentos y permisos a medida." }, { title: "Soporte dedicado", body: "Mesa de ejecución y equipos post-trade en su zona horaria." }] },
    brokerages: { title: "Brókers", intro: "Amplíe su oferta con cobertura multiactivo, ejecución competitiva y un back office escalable.", highlights: [{ title: "Cuentas ómnibus y subcuentas", body: "Estructuras de cuenta flexibles para clientes finales." }, { title: "Marca blanca", body: "Una interfaz de trading lista para usar con su marca." }, { title: "Soporte dedicado", body: "Onboarding, mesa de ejecución y conciliación." }] },
    "asset-managers": { title: "Gestores de activos", intro: "Ejecute en mercados globales desde una única cuenta multidivisa con informes y custodia institucionales.", highlights: [{ title: "Ejecución multiactivo", body: "Divisas, materias primas, índices, acciones, renta fija, metales y activos digitales." }, { title: "Paneles de cartera", body: "Riesgo, exposición y P&L en tiempo real." }, { title: "Soporte dedicado", body: "Un gestor de relación respaldado por nuestra mesa de ejecución." }] },
    "family-offices": { title: "Family offices", intro: "Servicio discreto y personalizado con diversificación global y custodia segura.", highlights: [{ title: "Diversificación global", body: "Acceso a mercados cotizados y OTC en todo el mundo." }, { title: "Custodia segura", body: "Activos segregados en custodios consolidados." }, { title: "Soporte dedicado", body: "Un único punto de contacto para cada solicitud." }] },
    "professional-traders": { title: "Traders profesionales", intro: "Ejecución de baja latencia, profundidad de mercado en vivo y herramientas algorítmicas creadas por ingenieros que operan.", highlights: [{ title: "Profundidad de mercado en vivo", body: "Transparencia total del libro de órdenes en todos los mercados." }, { title: "Ejecución algorítmica", body: "Automatice entradas y salidas con órdenes basadas en reglas." }, { title: "Controles de riesgo", body: "Dimensionamiento de posiciones, cortacircuitos y límites de exposición en tiempo real." }] },
    "individual-investors": { title: "Inversores particulares", intro: "Acceda a nuevas clases de activos con una sola cuenta y una plataforma que crece con usted.", highlights: [{ title: "Nuevas clases de activos", body: "Acciones, índices, metales y activos digitales desde una sola cuenta." }, { title: "Comisiones transparentes", body: "Comisiones de ejecución y financiación claras y acordadas de antemano." }, { title: "Soporte dedicado", body: "Atención humana cuando la necesite." }] },
  },
  assetClasses: [
    { label: "Divisas", body: "FX al contado: pares mayores, menores y exóticos con liquidez ECN de primer nivel." },
    { label: "Materias primas", body: "Futuros de energía, agrícolas y metales en las principales bolsas." },
    { label: "Índices bursátiles", body: "Futuros y CFD sobre índices globales con liquidez profunda." },
    { label: "Acciones y ETF", body: "Acciones y ETF cotizados en mercados de EE. UU., Europa y Asia." },
    { label: "Renta fija", body: "Bonos soberanos y corporativos, cotizados y OTC." },
    { label: "Metales", body: "Oro, plata, platino y paladio, al contado y futuros." },
    { label: "Activos digitales", body: "Principales activos digitales a través de mercados regulados, 24/7." },
  ],
  technologyFeatures: [
    { title: "Modelos ML propios", body: "Sistemas de aprendizaje adaptativo entrenados con décadas de datos de mercado." },
    { title: "Ejecución de latencia ultrabaja", body: "Servidores colocalizados, acceso directo al mercado y enrutamiento inteligente de órdenes." },
    { title: "Gestión avanzada del riesgo", body: "Dimensionamiento automático de posiciones, cortacircuitos y pruebas de estrés." },
    { title: "Conectividad multimercado", body: "Conexiones directas con más de 50 mercados regulados y proveedores de liquidez." },
    { title: "Agregación de datos en tiempo real", body: "Millones de datos de mercado por segundo, normalizados y validados." },
    { title: "Seguridad de nivel bancario", body: "Cifrado, autenticación multifactor y módulos de seguridad hardware." },
    { title: "Paneles de cartera", body: "Riesgo, exposición y P&L en tiempo real." },
    { title: "Soluciones de marca blanca", body: "Su marca sobre nuestra infraestructura, diseñada para el control." },
  ],
  rateCategories: [
    { title: "Comisiones de ejecución", body: "Comisiones por instrumento acordadas en su tarifario, comunicadas antes de cada operación." },
    { title: "Financiación", body: "Financiación overnight de posiciones apalancadas, por instrumento y divisa." },
    { title: "Costes de préstamo", body: "Costes de préstamo de acciones y activos para posiciones cortas, comunicados antes de la ejecución." },
    { title: "Datos y conectividad", body: "Datos de mercado y conectividad API a tarifas fijas publicadas." },
    { title: "Custodia y liquidación", body: "Comisiones de custodia, liquidación y retirada recogidas en su tarifario." },
    { title: "Inactividad", body: "Se aplica solo tras un periodo prolongado sin actividad." },
  ],
  pages: {
    ctaBand: { title: "Donde el capital se encuentra con la inteligencia de las máquinas.", body: "Hable con nuestro equipo sobre onboarding, comisiones e integración.", cta: { label: "Contáctenos" } },
    clients: {
      metaTitle: "Clientes: instituciones, family offices y traders",
      metaDescription: "Por qué bancos, brókers, gestores de activos, family offices y traders profesionales eligen NUUK.",
      kicker: "Clientes",
      title: "Nuestros clientes",
      intro: "De los bancos a los inversores particulares, NUUK ofrece una plataforma, una cuenta y un único punto de contacto.",
      whyTitle: "Por qué los profesionales eligen NUUK",
      reasons: [
        { title: "Disciplina institucional", body: "Gobernanza sistemática en ejecución, riesgo e informes." },
        { title: "La confianza de los profesionales", body: "Diseñado para instituciones e inversores profesionales, del DIFC al mundo." },
        { title: "Acceso a más de 50 mercados", body: "Una cuenta multidivisa, todas las grandes clases de activos." },
        { title: "Tecnología institucional", body: "Plataforma propia, API FIX/HTTP y análisis impulsados por IA." },
        { title: "Siempre disponibles", body: "Un equipo global y una mesa de ejecución en su zona horaria." },
      ],
      whoTitle: "A quién servimos",
      ctaTitle: "Inicie la conversación adecuada",
    },
    audience: { kicker: "Clientes", supportTitle: "Soporte dedicado", supportBody: "Un gestor de relación, una mesa de ejecución y un equipo de ingeniería en su zona horaria." },
    markets: {
      metaTitle: "Mercados: cobertura multiactivo en más de 50 mercados",
      metaDescription: "Divisas, materias primas, índices, acciones, renta fija, metales y activos digitales desde una única cuenta multidivisa.",
      kicker: "Mercados",
      title: "Mercados",
      intro: "Opere en los mercados más líquidos del mundo desde una única cuenta multidivisa.",
      cta: { label: "Empezar" },
      kpis: [["50+", "mercados regulados"], ["150+", "modelos de IA activos"], ["<5ms", "latencia media de ejecución"]],
      assetsTitle: "Clases de activos",
      features: [
        { title: "Acceso global a mercados", body: "Una cuenta para mercados de América, Europa, Oriente Medio y Asia." },
        { title: "Custodia segura de activos", body: "Activos de los clientes segregados en custodios consolidados." },
        { title: "Margen cruzado", body: "Margen a nivel de cartera entre clases de activos." },
        { title: "Tecnología propia", body: "Plataforma web, API FIX/HTTP y análisis impulsados por IA." },
      ],
      depositsTitle: "Depósitos multidivisa",
      depositsBody: "Financie su cuenta en USD, EUR, GBP, AED y otras divisas principales. Mantenga saldos en varias divisas a la vez y liquide operaciones sin conversión forzosa.",
    },
    pricing: {
      metaTitle: "Estructura de comisiones",
      metaDescription: "Comisiones de ejecución, financiación, datos y custodia claras y acordadas de antemano.",
      kicker: "Mercados",
      title: "Estructura de comisiones",
      intro: "Comisiones de ejecución, financiación, datos y custodia claras y acordadas de antemano. Sin márgenes ocultos.",
      cta: { label: "Solicitar tarifario" },
      assetsTitle: "Clases de activos",
      assetNote: "Comisión y financiación: según su tarifario",
      ratesTitle: "Por qué paga",
      ctaTitle: "Solicite su tarifario",
      ctaBody: "Los clientes institucionales y profesionales reciben un tarifario a medida antes del onboarding.",
    },
    technology: {
      metaTitle: "Tecnología de trading: plataforma, API e IA",
      metaDescription: "Plataforma web propia, API FIX y HTTP, marca blanca e inteligencia de mercado impulsada por IA.",
      kicker: "Tecnología",
      title: "Tecnología propia",
      intro: "Sistemas de nivel empresarial diseñados para velocidad, fiabilidad y rendimiento: aprendizaje automático, ejecución de baja latencia y control de riesgo en una sola pila.",
      cta: { label: "Solicitar demo" },
      stackTitle: "Pila tecnológica avanzada",
      httpTitle: "API HTTP",
      httpBody: "Endpoints REST para datos de mercado, órdenes, posiciones e informes. Ideal para herramientas de cartera, paneles y estrategias automatizadas. Sin compromiso mínimo.",
      fixTitle: "API FIX",
      fixBody: "Sesiones FIX 4.4 de baja latencia para enrutamiento de órdenes y drop-copy, colocalizadas en los centros de trading globales para una calidad de ejecución institucional.",
      aiTitle: "Inteligencia artificial de nueva generación",
      ai: [
        { title: "Redes de aprendizaje profundo", body: "Redes neuronales multicapa entrenadas con miles de millones de datos, que combinan LSTM, transformers y aprendizaje por refuerzo." },
        { title: "Motor de análisis predictivo", body: "Modelos de previsión que analizan sentimiento, flujo de órdenes, volatilidad e indicadores macro, validados continuamente con resultados reales." },
        { title: "Gobernanza del riesgo", body: "Límites de exposición en tiempo real, cortacircuitos y pruebas de estrés protegen el capital las 24 horas." },
      ],
      infraTitle: "Infraestructura global de trading",
      infraBody: "Conexiones directas con más de 50 mercados regulados y proveedores de liquidez, con arquitectura de red redundante, agregación de datos en tiempo real y seguridad de nivel bancario. Despliegues de marca blanca disponibles para socios.",
      infraCta: { label: "Hable con nuestros ingenieros" },
    },
    company: {
      metaTitle: "Sobre NUUK: infraestructura de trading diseñada con IA",
      metaDescription: "NUUK es una empresa de trading cuantitativo e infraestructura diseñada con IA con sede en el DIFC, Dubái.",
      kicker: "Nosotros",
      title: "Nuestra historia",
      intro: "NUUK es una empresa de trading cuantitativo e infraestructura diseñada con IA. Combinamos algoritmos propios, sistemas de ejecución institucionales y una red global de mercados para ofrecer a los profesionales un acceso disciplinado a los mercados mundiales.",
      principlesTitle: "Principios rectores",
      principles: [
        { title: "Disciplina", body: "Cada decisión es sistemática, con riesgo controlado y auditable." },
        { title: "Transparencia", body: "Precios claros, informes claros y comunicación clara." },
        { title: "Ingeniería", body: "Construimos nuestras propias plataformas, modelos y conectividad." },
        { title: "Colaboración", body: "Un gestor de relación que conoce su negocio." },
      ],
      deliverTitle: "Usted impulsa el cambio, nosotros lo hacemos realidad",
      deliverBody: "Nuestra infraestructura se conecta a una red diversificada de mercados globales regulados y proveedores de liquidez, lo que permite una ejecución automatizada multimercado con integridad de datos, eficiencia de latencia y gobernanza sistemática completa.",
      ctaTitle: "Equipo internacional, presencia local",
      ctaBody: "Con sede en el DIFC, Dubái, atendemos a clientes en todas las zonas horarias.",
    },
    contact: {
      metaTitle: "Contáctenos",
      metaDescription: "Hable con nuestro equipo sobre onboarding, comisiones e integración.",
      kicker: "Nosotros",
      title: "Contáctenos",
      intro: "Atención al cliente, gestión de cuentas y consultas.",
      supportTitle: "Atención al cliente",
      managerTitle: "Hable con nuestro equipo en Dubái",
      formTitle: "Sugerencias y consultas",
      form: {
        name: "Nombre",
        namePlaceholder: "Su nombre",
        email: "Correo electrónico",
        emailPlaceholder: "usted@empresa.com",
        company: "Empresa (opcional)",
        companyPlaceholder: "Empresa",
        message: "Mensaje",
        messagePlaceholder: "¿Cómo podemos ayudarle?",
        submit: "Enviar consulta",
        note: "Se abrirá su cliente de correo con el mensaje precargado. No se almacena ningún dato en este sitio.",
        errorRequired: "Indique su nombre, correo electrónico y mensaje.",
        errorEmail: "Introduzca una dirección de correo válida.",
        subject: "Consulta de",
      },
      ctaBody: "Las consultas institucionales y profesionales se responden en un día laborable.",
      ctaLabel: "Escríbanos",
    },
    footer: {
      copyright: "Todos los derechos reservados.",
      legal1: "es una empresa de trading cuantitativo e infraestructura de trading diseñada con IA, con sede en el Dubai International Financial Centre. Los servicios se ofrecen a clientes profesionales e institucionales; su disponibilidad depende de su jurisdicción y de la normativa aplicable.",
      legal2: "La información de este sitio web se facilita únicamente con fines informativos y no constituye asesoramiento de inversión ni una oferta o solicitud de compra o venta de ningún instrumento o servicio financiero.",
      risk1: "Operar conlleva un riesgo sustancial. Invertir en divisas, materias primas, índices, acciones, renta fija, metales y activos digitales puede generar pérdidas superiores a la inversión inicial, y operar con margen conlleva riesgo adicional. El rendimiento pasado de cualquier modelo, estrategia o sistema no garantiza resultados futuros. Asegúrese de comprender estos riesgos antes de contratar cualquier servicio.",
      risk2: "Las cifras de mercado y la telemetría del sistema mostradas en este sitio son ilustrativas y pueden tener retraso. Solo consultas institucionales.",
      risk3: "Compruebe que cualquier comunicación que diga proceder de NUUK provenga del dominio nuukquant.com. Notifique cualquier posible uso indebido de nuestro nombre a",
    },
  },
};
