import type { ContentOverride } from "@/i18n";

export const es: ContentOverride = {
  meta: {
    title: "NUUK — Infraestructura financiera basada en IA",
    description:
      "Infraestructura de trading cuantitativo y ejecución de órdenes basada en inteligencia artificial para instituciones e inversores profesionales. Divisas, materias primas, índices, acciones y activos digitales en más de 50 mercados.",
  },
  brand: { office: "Dubai International Financial Centre (DIFC), Dubái, Emiratos Árabes Unidos" },
  ui: {
    contact: "Contacto",
    getStarted: "Solicitar acceso",
    contactUs: "Contactar",
    learnMore: "Más información",
    language: "Idioma",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
    home: "Página de inicio de NUUK",
    noPosts: "Todavía no hay publicaciones en esta sección.",
    riskDisclosure: "Advertencia sobre riesgos",
  },
  nav: [
    { label: "Clientes", items: [{ label: "Bancos" }, { label: "Sociedades de valores" }, { label: "Gestoras de activos" }, { label: "Family offices" }, { label: "Traders profesionales" }, { label: "Inversores particulares" }] },
    { label: "Mercados", items: [{ label: "Todos los mercados" }, { label: "Divisas" }, { label: "Materias primas" }, { label: "Índices bursátiles" }, { label: "Acciones y ETF" }, { label: "Renta fija" }, { label: "Metales preciosos" }, { label: "Activos digitales" }, { label: "Tarifas" }] },
    { label: "Tecnología", items: [{ label: "Plataforma" }, { label: "Integración API" }, { label: "Inteligencia artificial" }, { label: "Infraestructura" }] },
    { label: "Análisis", items: [{ label: "Análisis de mercado" }, { label: "Prensa" }, { label: "Eventos" }] },
    { label: "Sobre nosotros", items: [{ label: "Nuestra historia" }, { label: "Contactar" }, { label: "Empleo" }] },
  ],
  legalLinks: [{ label: "Advertencia sobre riesgos" }, { label: "Política de privacidad" }, { label: "Condiciones de uso" }, { label: "Cookies" }, { label: "Tarifas" }],
  home: {
    hero: {
      title: ["Precisión.", "Inteligencia.", "Ejecución."],
      kicker: "INFRAESTRUCTURA DE TRADING BASADA EN IA",
      body: "NUUK es una empresa de trading cuantitativo basada en inteligencia artificial que opera en los mercados financieros internacionales. Desarrollamos algoritmos propios, modelos de aprendizaje automático y sistemas de ejecución de nivel institucional para operar con disciplina y con el riesgo bajo control en divisas, materias primas, índices, acciones y activos digitales.",
      cta: { label: "Contactar" },
    },
    audiences: [{ label: "Bancos" }, { label: "Sociedades de valores" }, { label: "Gestoras de activos" }, { label: "Family offices" }, { label: "Traders profesionales" }, { label: "Inversores particulares" }],
    core: [
      { title: ["Cobertura", "multiactivo"], body: "Divisas, materias primas, índices bursátiles, acciones, renta fija, metales preciosos y activos digitales, a través de una amplia red de mercados regulados y proveedores de liquidez." },
      { title: ["Tecnología", "propia"], body: "Modelos de aprendizaje automático desarrollados internamente, ejecución de órdenes con latencia ultrabaja y una plataforma web con acceso mediante API FIX y HTTP." },
      { title: ["Tarifas", "transparentes"], body: "Comisiones de ejecución, financiación y datos claras y acordadas de antemano. Sin costes ocultos." },
      { title: ["Servicio", "institucional"], body: "Un gestor de relación dedicado, respaldado por nuestra mesa de ejecución, el equipo de riesgos y los ingenieros." },
    ],
    servicing: {
      title: "Un único equipo al servicio de instituciones e inversores profesionales en todo el mundo",
      items: ["Alta estructurada, con acceso a la plataforma y a las herramientas API desde el primer día", "Cobertura de todas las zonas horarias desde nuestra sede en el DIFC de Dubái", "Apoyo de la mesa de ejecución para órdenes en bloque, extrabursátiles y en varios mercados", "Informes posteriores a la negociación, conciliación y análisis de riesgos"],
      cta: { label: "Solicitar acceso" },
    },
    network: { title: "Nuestra red de colaboradores", partners: ["ECN de divisas de primer nivel", "Bolsas internacionales de derivados", "Mercados de índices bursátiles", "Mercados de activos digitales", "Custodios de primer nivel", "Proveedores de liquidez"] },
    experts: {
      title: "Plataforma de trading propia",
      items: [
        { title: "Desarrollada por nuestros ingenieros", body: "Una plataforma web y un motor de ejecución diseñados internamente, disponibles desde una única cuenta multidivisa." },
        { title: "Personalización e integraciones", body: "API FIX y HTTP, conjuntos de instrumentos a medida y soluciones de marca blanca para los socios que necesiten su propia interfaz." },
        { title: "Infraestructura distribuida", body: "Infraestructura redundante alojada junto a las bolsas de las principales plazas financieras, con una latencia interna inferior a un milisegundo." },
      ],
      cta: { label: "Más información" },
      imageAlt: "Plataforma de trading NUUK en ordenador de sobremesa, portátil y teléfono",
    },
    exchanges: {
      title: "Acceso a los mercados internacionales",
      groups: [
        [{ city: "Nueva York, Estados Unidos" }, { city: "Chicago, Estados Unidos" }, { city: "Atlanta, Estados Unidos" }],
        [{ city: "Londres, Reino Unido" }, { city: "Fráncfort, Alemania" }, { city: "Zúrich, Suiza" }],
        [{ city: "Dubái, Emiratos Árabes Unidos" }, { city: "Abu Dabi, Emiratos Árabes Unidos" }],
        [{ city: "Hong Kong" }, { city: "Singapur" }, { city: "Tokio, Japón" }],
      ],
    },
    broker: {
      title: "Cimentado en el buen gobierno",
      body: "Nuestra infraestructura está conectada a una amplia red de mercados regulados, custodios y proveedores de liquidez. Esto permite ejecutar órdenes de forma automatizada en varios mercados, con integridad de los datos, latencia mínima y un control sistemático completo.",
      cta: { label: "Sobre NUUK" },
      items: [
        { title: "Control sistemático", body: "Cada decisión se basa en reglas, queda registrada y es auditable." },
        { title: "Contrapartes de confianza", body: "Exclusivamente mercados regulados y proveedores de liquidez consolidados." },
        { title: "Custodia segura", body: "Los activos de los clientes se mantienen en custodios consolidados." },
        { title: "Segregación de activos", body: "Los activos de los clientes se mantienen separados de los fondos de la empresa." },
      ],
    },
    pulse: {
      title: "Análisis de NUUK",
      tabs: ["Todas las publicaciones", "Análisis", "Prensa", "Eventos"],
      posts: [
        { title: "Tipos de interés, crecimiento y dólar de cara al cierre del año", excerpt: "Lo que descuentan nuestros modelos macroeconómicos en divisas y tipos mientras el mercado reevalúa la senda de la política monetaria.", tag: "Análisis", date: "4 de septiembre de 2026" },
        { title: "El oro cerca de máximos históricos: la lectura de nuestro motor de señales", excerpt: "Los metales preciosos mantienen la demanda mientras se relajan los rendimientos reales. Repaso a nuestras señales de momentum y reversión a la media.", tag: "Análisis", date: "3 de septiembre de 2026" },
        { title: "NUUK amplía su conectividad con los mercados", excerpt: "Nuevas conexiones directas aumentan la profundidad de liquidez en divisas, futuros y activos digitales.", tag: "Prensa", date: "2 de septiembre de 2026" },
        { title: "Mesas redondas institucionales en el DIFC este otoño", excerpt: "Le invitamos a una serie de sesiones a puerta cerrada sobre la IA en la ejecución de órdenes y la gestión de riesgos.", tag: "Evento", date: "1 de septiembre de 2026" },
      ],
    },
  },
  audiences: {
    banks: { title: "Bancos", intro: "Ejecución de órdenes, conectividad y análisis basados en IA para bancos que necesitan acceso multiactivo a los mercados a través de una única contraparte rigurosa.", highlights: [{ title: "API directa", body: "Conectividad FIX y HTTP para el enrutamiento de órdenes, los datos de mercado y los informes." }, { title: "Marca blanca", body: "Ofrezca nuestra plataforma con su marca, con instrumentos y permisos a medida." }, { title: "Atención dedicada", body: "Mesa de ejecución y equipos de post-negociación en su zona horaria." }] },
    brokerages: { title: "Sociedades de valores", intro: "Amplíe su oferta con cobertura multiactivo, ejecución competitiva y un back office escalable.", highlights: [{ title: "Cuentas ómnibus y subcuentas", body: "Estructuras de cuenta flexibles adaptadas a sus clientes finales." }, { title: "Marca blanca", body: "Una interfaz de negociación lista para usar con su imagen corporativa." }, { title: "Atención dedicada", body: "Alta de clientes, mesa de ejecución y conciliación." }] },
    "asset-managers": { title: "Gestoras de activos", intro: "Ejecute órdenes en los mercados internacionales desde una única cuenta multidivisa, con informes y custodia de nivel institucional.", highlights: [{ title: "Ejecución multiactivo", body: "Divisas, materias primas, índices, acciones, renta fija, metales preciosos y activos digitales." }, { title: "Paneles de cartera", body: "Riesgo, exposición y resultados en tiempo real." }, { title: "Atención dedicada", body: "Un gestor de relación respaldado por nuestra mesa de ejecución." }] },
    "family-offices": { title: "Family offices", intro: "Un servicio discreto y personalizado, con diversificación internacional y custodia segura de los activos.", highlights: [{ title: "Diversificación internacional", body: "Acceso a mercados regulados y extrabursátiles de todo el mundo." }, { title: "Custodia segura", body: "Activos segregados en custodios consolidados." }, { title: "Atención dedicada", body: "Un único interlocutor para todas sus solicitudes." }] },
    "professional-traders": { title: "Traders profesionales", intro: "Ejecución de baja latencia, profundidad de mercado en tiempo real y herramientas algorítmicas creadas por ingenieros que conocen los mercados.", highlights: [{ title: "Profundidad de mercado en tiempo real", body: "Transparencia total del libro de órdenes en todos los mercados." }, { title: "Ejecución algorítmica", body: "Automatice entradas y salidas con órdenes basadas en reglas." }, { title: "Control de riesgos", body: "Dimensionamiento de posiciones, mecanismos de parada automática y límites de exposición en tiempo real." }] },
    "individual-investors": { title: "Inversores particulares", intro: "Acceda a nuevas clases de activos con una sola cuenta y una plataforma que evoluciona con usted.", highlights: [{ title: "Nuevas clases de activos", body: "Acciones, índices, metales preciosos y activos digitales desde una única cuenta." }, { title: "Comisiones transparentes", body: "Comisiones de ejecución y financiación claras y acordadas de antemano." }, { title: "Atención dedicada", body: "Atención personal cuando la necesite." }] },
  },
  assetClasses: [
    { label: "Divisas", body: "Pares principales, secundarios y exóticos en el mercado al contado, con liquidez ECN de primer nivel." },
    { label: "Materias primas", body: "Futuros sobre energía, productos agrícolas y metales en las principales bolsas." },
    { label: "Índices bursátiles", body: "Futuros y CFD sobre los principales índices internacionales, con liquidez profunda." },
    { label: "Acciones y ETF", body: "Acciones y fondos cotizados en los mercados de Estados Unidos, Europa y Asia." },
    { label: "Renta fija", body: "Bonos soberanos y corporativos, cotizados y extrabursátiles." },
    { label: "Metales preciosos", body: "Oro, plata, platino y paladio, al contado y a plazo." },
    { label: "Activos digitales", body: "Los principales activos digitales a través de mercados regulados, las 24 horas." },
  ],
  technologyFeatures: [
    { title: "Modelos propios de aprendizaje automático", body: "Sistemas de aprendizaje adaptativo entrenados con décadas de datos de mercado." },
    { title: "Ejecución de latencia ultrabaja", body: "Servidores alojados junto a las bolsas, acceso directo al mercado y enrutamiento inteligente de órdenes." },
    { title: "Gestión avanzada de riesgos", body: "Dimensionamiento automático de posiciones, mecanismos de parada automática y pruebas de estrés." },
    { title: "Conectividad con múltiples mercados", body: "Conexiones directas con más de 50 mercados regulados y proveedores de liquidez." },
    { title: "Agregación de datos en tiempo real", body: "Millones de datos de mercado por segundo, normalizados y validados." },
    { title: "Seguridad de nivel bancario", body: "Cifrado, autenticación multifactor y módulos de seguridad hardware." },
    { title: "Paneles de cartera", body: "Riesgo, exposición y resultados en tiempo real." },
    { title: "Soluciones de marca blanca", body: "Su marca sobre nuestra infraestructura, diseñada para que el control siga siendo suyo." },
  ],
  rateCategories: [
    { title: "Comisiones de ejecución", body: "Comisiones por instrumento fijadas en su tarifa y comunicadas antes de cada operación." },
    { title: "Financiación", body: "Coste de financiación a un día de las posiciones apalancadas, definido por instrumento y divisa." },
    { title: "Costes de préstamo de valores", body: "Costes de préstamo de valores para posiciones cortas, comunicados antes de la ejecución." },
    { title: "Datos y conectividad", body: "Datos de mercado y conectividad API a tarifas fijas y publicadas." },
    { title: "Custodia y liquidación", body: "Las comisiones de custodia, liquidación y retirada de fondos figuran en su tarifa." },
    { title: "Inactividad de la cuenta", body: "Se aplica únicamente tras un periodo prolongado sin operaciones." },
  ],
  pages: {
    ctaBand: { title: "Donde el capital se encuentra con la inteligencia artificial.", body: "Hable con nuestro equipo sobre el alta, las tarifas y la integración.", cta: { label: "Contactar" } },
    clients: {
      metaTitle: "Clientes: instituciones, family offices y traders",
      metaDescription: "Por qué bancos, sociedades de valores, gestoras de activos, family offices y traders profesionales eligen NUUK.",
      kicker: "Clientes",
      title: "Nuestros clientes",
      intro: "Desde bancos hasta inversores particulares, NUUK ofrece una única plataforma, una única cuenta y un único interlocutor.",
      whyTitle: "Por qué los profesionales eligen NUUK",
      reasons: [
        { title: "Disciplina institucional", body: "Control sistemático de la ejecución, los riesgos y los informes." },
        { title: "La confianza de los profesionales", body: "Diseñado para instituciones e inversores profesionales, desde el DIFC hacia el mundo." },
        { title: "Acceso a más de 50 mercados", body: "Una única cuenta multidivisa y todas las grandes clases de activos." },
        { title: "Tecnología institucional", body: "Plataforma propia, API FIX/HTTP y análisis basados en IA." },
        { title: "Siempre disponibles", body: "Un equipo internacional y una mesa de ejecución en su zona horaria." },
      ],
      whoTitle: "A quién atendemos",
      ctaTitle: "Iniciemos la conversación",
    },
    audience: { kicker: "Clientes", supportTitle: "Atención dedicada", supportBody: "Un gestor de relación, una mesa de ejecución y un equipo de ingeniería en su zona horaria." },
    markets: {
      metaTitle: "Mercados: cobertura multiactivo en más de 50 mercados",
      metaDescription: "Divisas, materias primas, índices bursátiles, acciones, renta fija, metales preciosos y activos digitales desde una única cuenta multidivisa.",
      kicker: "Mercados",
      title: "Mercados",
      intro: "Opere en los mercados más líquidos del mundo desde una única cuenta multidivisa.",
      cta: { label: "Solicitar acceso" },
      kpis: [["50+", "mercados regulados"], ["150+", "modelos de IA en producción"], ["<5ms", "latencia media de ejecución"]],
      assetsTitle: "Clases de activos",
      features: [
        { title: "Acceso a los mercados internacionales", body: "Una única cuenta para los mercados de América, Europa, Oriente Medio y Asia." },
        { title: "Custodia segura de activos", body: "Activos de los clientes segregados en custodios consolidados." },
        { title: "Margen cruzado", body: "Cálculo del margen a nivel de cartera entre todas las clases de activos." },
        { title: "Tecnología propia", body: "Plataforma web, API FIX/HTTP y análisis basados en IA." },
      ],
      depositsTitle: "Cuenta multidivisa",
      depositsBody: "Ingrese fondos en USD, EUR, GBP, AED y otras divisas principales. Mantenga saldos en varias divisas a la vez y liquide sus operaciones sin conversiones forzosas.",
    },
    pricing: {
      metaTitle: "Tarifas",
      metaDescription: "Comisiones de ejecución, financiación, datos y custodia claras y acordadas de antemano.",
      kicker: "Mercados",
      title: "Tarifas",
      intro: "Comisiones de ejecución, financiación, datos y custodia claras y acordadas de antemano. Sin costes ocultos.",
      cta: { label: "Solicitar tarifas" },
      assetsTitle: "Clases de activos",
      assetNote: "Comisiones y financiación: según su tarifa",
      ratesTitle: "Conceptos de la tarifa",
      ctaTitle: "Solicite su tarifa",
      ctaBody: "Los clientes institucionales y profesionales reciben una tarifa personalizada antes del alta.",
    },
    technology: {
      metaTitle: "Tecnología de trading: plataforma, API e IA",
      metaDescription: "Plataforma web propia, API FIX y HTTP, soluciones de marca blanca y análisis de mercado basados en IA.",
      kicker: "Tecnología",
      title: "Tecnología propia",
      intro: "Sistemas de nivel institucional diseñados para la velocidad, la fiabilidad y el rendimiento: aprendizaje automático, ejecución de baja latencia y control de riesgos en una única arquitectura.",
      cta: { label: "Solicitar una demostración" },
      stackTitle: "Una arquitectura tecnológica avanzada",
      httpTitle: "API HTTP",
      httpBody: "Puntos de acceso REST para datos de mercado, órdenes, posiciones e informes. Ideal para herramientas de gestión de carteras, paneles de control y estrategias automatizadas. Sin compromiso mínimo.",
      fixTitle: "API FIX",
      fixBody: "Sesiones FIX 4.4 de baja latencia para el enrutamiento de órdenes y el drop copy, alojadas junto a las bolsas de las principales plazas financieras para garantizar una calidad de ejecución institucional.",
      aiTitle: "Inteligencia artificial de nueva generación",
      ai: [
        { title: "Redes de aprendizaje profundo", body: "Redes neuronales multicapa entrenadas con miles de millones de datos, que combinan LSTM, transformers y aprendizaje por refuerzo." },
        { title: "Motor de análisis predictivo", body: "Modelos de previsión que analizan el sentimiento del mercado, el flujo de órdenes, la volatilidad y los indicadores macroeconómicos, validados de forma continua con resultados reales." },
        { title: "Gobierno del riesgo", body: "Límites de exposición en tiempo real, mecanismos de parada automática y pruebas de estrés protegen el capital de forma permanente." },
      ],
      infraTitle: "Infraestructura de trading internacional",
      infraBody: "Conexiones directas con más de 50 mercados regulados y proveedores de liquidez, arquitectura de red redundante, agregación de datos en tiempo real y seguridad de nivel bancario. Soluciones de marca blanca disponibles para socios.",
      infraCta: { label: "Hablar con nuestros ingenieros" },
    },
    company: {
      metaTitle: "Sobre NUUK: infraestructura de trading basada en IA",
      metaDescription: "NUUK es una empresa de trading cuantitativo e infraestructura de trading basada en IA con sede en el DIFC de Dubái.",
      kicker: "Sobre nosotros",
      title: "Nuestra historia",
      intro: "NUUK es una empresa de trading cuantitativo e infraestructura de trading basada en inteligencia artificial. Combinamos algoritmos propios, sistemas de ejecución de nivel institucional y una red internacional de mercados para ofrecer a los profesionales un acceso disciplinado a los mercados mundiales.",
      principlesTitle: "Nuestros principios",
      principles: [
        { title: "Disciplina", body: "Cada decisión es sistemática, tiene el riesgo controlado y es auditable." },
        { title: "Transparencia", body: "Tarifas claras, informes claros y comunicación clara." },
        { title: "Ingeniería", body: "Desarrollamos nuestras propias plataformas, modelos y conexiones." },
        { title: "Colaboración", body: "Un gestor de relación que conoce su negocio." },
      ],
      deliverTitle: "Usted marca el rumbo; nosotros lo ejecutamos",
      deliverBody: "Nuestra infraestructura está conectada a una amplia red de mercados internacionales regulados y proveedores de liquidez, lo que permite ejecutar órdenes de forma automatizada en varios mercados con integridad de los datos, latencia mínima y un control sistemático completo.",
      ctaTitle: "Equipo internacional, presencia local",
      ctaBody: "Con sede en el DIFC de Dubái, atendemos a nuestros clientes en todas las zonas horarias.",
    },
    contact: {
      metaTitle: "Contactar",
      metaDescription: "Hable con nuestro equipo sobre el alta, las tarifas y la integración.",
      kicker: "Sobre nosotros",
      title: "Contactar",
      intro: "Atención al cliente, seguimiento de cuentas y consultas.",
      supportTitle: "Atención al cliente",
      managerTitle: "Hable con nuestro equipo en Dubái",
      formTitle: "Sugerencias y consultas",
      form: {
        name: "Nombre",
        namePlaceholder: "Nombre y apellidos",
        email: "Correo electrónico",
        emailPlaceholder: "nombre@empresa.com",
        company: "Empresa (opcional)",
        companyPlaceholder: "Nombre de la empresa",
        message: "Mensaje",
        messagePlaceholder: "¿En qué podemos ayudarle?",
        submit: "Enviar",
        note: "Se abrirá su aplicación de correo con el mensaje ya redactado. Este sitio no almacena ningún dato.",
        errorRequired: "Indique su nombre, su correo electrónico y el mensaje.",
        errorEmail: "Introduzca una dirección de correo electrónico válida.",
        subject: "Consulta de",
      },
      ctaBody: "Las consultas institucionales y profesionales se responden en el plazo de un día laborable.",
      ctaLabel: "Escríbanos",
    },
    footer: {
      copyright: "Todos los derechos reservados.",
      legal1: "es una empresa de trading cuantitativo e infraestructura de trading basada en inteligencia artificial, con sede en el Dubai International Financial Centre. Sus servicios se dirigen a clientes profesionales e institucionales; su disponibilidad depende de la jurisdicción del cliente y de la normativa aplicable.",
      legal2: "La información contenida en este sitio web tiene un carácter meramente informativo y no constituye asesoramiento de inversión ni una oferta o solicitud de compra o venta de ningún instrumento o servicio financiero.",
      risk1: "Operar en los mercados financieros conlleva riesgos significativos. La inversión en divisas, materias primas, índices, acciones, renta fija, metales preciosos y activos digitales puede generar pérdidas superiores al capital invertido, y operar con apalancamiento conlleva riesgos adicionales. La rentabilidad pasada de cualquier modelo, estrategia o sistema no garantiza resultados futuros. Asegúrese de comprender estos riesgos antes de contratar cualquier servicio.",
      risk2: "Los datos de mercado y los indicadores de sistema mostrados en este sitio son ilustrativos y pueden presentar retrasos. Solo se atienden consultas institucionales.",
      risk3: "Compruebe que cualquier comunicación que se atribuya a NUUK procede del dominio nuukquant.com. Cualquier sospecha de uso indebido de nuestro nombre puede comunicarse a",
    },
  },
};
