import type { ContentOverride } from "@/i18n";

export const fr: ContentOverride = {
  meta: {
    title: "NUUK — Infrastructure financière fondée sur l'IA",
    description:
      "Infrastructure de trading quantitatif et d'exécution des ordres fondée sur l'intelligence artificielle, destinée aux institutions et aux investisseurs professionnels. Devises, matières premières, indices, actions et actifs numériques sur plus de 50 places de marché.",
  },
  brand: { office: "Dubai International Financial Centre (DIFC), Dubaï, Émirats arabes unis" },
  ui: {
    contact: "Contact",
    getStarted: "Nous rejoindre",
    contactUs: "Nous contacter",
    learnMore: "En savoir plus",
    language: "Langue",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    home: "Page d'accueil NUUK",
    noPosts: "Aucune publication dans cette rubrique pour le moment.",
    riskDisclosure: "Avertissement sur les risques",
  },
  nav: [
    { label: "Clients", items: [{ label: "Banques" }, { label: "Sociétés de courtage" }, { label: "Sociétés de gestion" }, { label: "Family offices" }, { label: "Traders professionnels" }, { label: "Investisseurs particuliers" }] },
    { label: "Marchés", items: [{ label: "Tous les marchés" }, { label: "Marché des changes" }, { label: "Matières premières" }, { label: "Indices boursiers" }, { label: "Actions et ETF" }, { label: "Obligations" }, { label: "Métaux précieux" }, { label: "Actifs numériques" }, { label: "Grille tarifaire" }] },
    { label: "Technologie", items: [{ label: "Plateforme" }, { label: "Intégration API" }, { label: "Intelligence artificielle" }, { label: "Infrastructure" }] },
    { label: "Analyses", items: [{ label: "Analyses de marché" }, { label: "Presse" }, { label: "Événements" }] },
    { label: "À propos", items: [{ label: "Notre histoire" }, { label: "Nous contacter" }, { label: "Carrières" }] },
  ],
  legalLinks: [{ label: "Avertissement sur les risques" }, { label: "Politique de confidentialité" }, { label: "Conditions d'utilisation" }, { label: "Cookies" }, { label: "Grille tarifaire" }],
  home: {
    hero: {
      title: ["Précision.", "Intelligence.", "Exécution."],
      kicker: "INFRASTRUCTURE DE TRADING FONDÉE SUR L'IA",
      body: "NUUK est une société de trading quantitatif fondée sur l'intelligence artificielle, présente sur les marchés financiers mondiaux. Nous développons des algorithmes propriétaires, des modèles d'apprentissage automatique et des systèmes d'exécution de niveau institutionnel, au service d'un trading discipliné et maîtrisé sur les devises, les matières premières, les indices, les actions et les actifs numériques.",
      cta: { label: "Nous contacter" },
    },
    audiences: [{ label: "Banques" }, { label: "Sociétés de courtage" }, { label: "Sociétés de gestion" }, { label: "Family offices" }, { label: "Traders professionnels" }, { label: "Investisseurs particuliers" }],
    core: [
      { title: ["Couverture", "multi-actifs"], body: "Devises, matières premières, indices boursiers, actions, obligations, métaux précieux et actifs numériques, accessibles via un vaste réseau de places de marché réglementées et de fournisseurs de liquidité." },
      { title: ["Technologie", "propriétaire"], body: "Modèles d'apprentissage automatique développés en interne, exécution des ordres à très faible latence et plateforme web dotée d'accès API FIX et HTTP." },
      { title: ["Grille tarifaire", "transparente"], body: "Des frais d'exécution, de financement et de données clairs et convenus à l'avance. Aucun coût caché." },
      { title: ["Service", "institutionnel"], body: "Un chargé de relation dédié, appuyé par notre table d'exécution, notre équipe de gestion des risques et nos ingénieurs." },
    ],
    servicing: {
      title: "Une seule équipe au service des institutions et des investisseurs professionnels dans le monde entier",
      items: ["Une entrée en relation structurée, avec accès à la plateforme et aux outils API dès le premier jour", "Une couverture de tous les fuseaux horaires depuis notre siège au DIFC, à Dubaï", "L'appui de notre table d'exécution pour les ordres de bloc, de gré à gré et multi-places", "Le reporting post-négociation, le rapprochement et l'analyse des risques"],
      cta: { label: "Nous rejoindre" },
    },
    network: { title: "Notre réseau de partenaires", partners: ["ECN de change de premier rang", "Bourses mondiales de produits dérivés", "Places de négociation d'indices", "Places d'actifs numériques", "Dépositaires de premier plan", "Fournisseurs de liquidité"] },
    experts: {
      title: "Plateforme de trading propriétaire",
      items: [
        { title: "Conçue par nos ingénieurs", body: "Une plateforme web et un moteur d'exécution développés en interne, accessibles depuis un compte unique multidevises." },
        { title: "Personnalisation et intégrations", body: "API FIX et HTTP, univers d'instruments sur mesure et solutions en marque blanche pour les partenaires souhaitant disposer de leur propre interface." },
        { title: "Infrastructure distribuée", body: "Une infrastructure redondante, hébergée à proximité des bourses dans les principales places financières, avec une latence interne inférieure à la milliseconde." },
      ],
      cta: { label: "En savoir plus" },
      imageAlt: "Plateforme de trading NUUK sur ordinateur de bureau, portable et smartphone",
    },
    exchanges: {
      title: "Accès aux marchés mondiaux",
      groups: [
        [{ city: "New York, États-Unis" }, { city: "Chicago, États-Unis" }, { city: "Atlanta, États-Unis" }],
        [{ city: "Londres, Royaume-Uni" }, { city: "Francfort, Allemagne" }, { city: "Zurich, Suisse" }],
        [{ city: "Dubaï, Émirats arabes unis" }, { city: "Abou Dhabi, Émirats arabes unis" }],
        [{ city: "Hong Kong" }, { city: "Singapour" }, { city: "Tokyo, Japon" }],
      ],
    },
    broker: {
      title: "Une gouvernance au cœur du dispositif",
      body: "Notre infrastructure est reliée à un vaste réseau de places de marché réglementées, de dépositaires et de fournisseurs de liquidité. Elle permet une exécution automatisée des ordres sur plusieurs places, avec une intégrité des données garantie, une latence maîtrisée et une gouvernance systématique complète.",
      cta: { label: "À propos de NUUK" },
      items: [
        { title: "Gouvernance systématique", body: "Chaque décision repose sur des règles, est journalisée et auditable." },
        { title: "Contreparties de confiance", body: "Uniquement des places réglementées et des fournisseurs de liquidité reconnus." },
        { title: "Conservation sécurisée", body: "Les actifs des clients sont conservés auprès de dépositaires reconnus." },
        { title: "Ségrégation des actifs", body: "Les actifs des clients sont tenus séparément des fonds de la société." },
      ],
    },
    pulse: {
      title: "Analyses NUUK",
      tabs: ["Toutes les publications", "Analyses", "Presse", "Événements"],
      posts: [
        { title: "Taux, croissance et dollar à l'approche de la fin d'année", excerpt: "Ce qu'intègrent nos modèles macroéconomiques sur les devises et les taux, alors que la trajectoire de la politique monétaire est réévaluée.", tag: "Analyse", date: "4 septembre 2026" },
        { title: "L'or proche de ses records : la lecture de notre moteur de signaux", excerpt: "Les métaux précieux restent recherchés tandis que les rendements réels se détendent. Focus sur nos signaux de momentum et de retour à la moyenne.", tag: "Analyse", date: "3 septembre 2026" },
        { title: "NUUK étend sa connectivité multi-places", excerpt: "De nouvelles connexions directes renforcent la profondeur de liquidité sur les places de change, de contrats à terme et d'actifs numériques.", tag: "Presse", date: "2 septembre 2026" },
        { title: "Tables rondes institutionnelles au DIFC cet automne", excerpt: "Rejoignez notre équipe pour une série de sessions à huis clos consacrées à l'IA dans l'exécution des ordres et la gestion des risques.", tag: "Événement", date: "1er septembre 2026" },
      ],
    },
  },
  audiences: {
    banks: { title: "Banques", intro: "Exécution des ordres, connectivité et analyses fondées sur l'IA pour les banques qui recherchent un accès multi-actifs aux marchés via une contrepartie unique et rigoureuse.", highlights: [{ title: "API directe", body: "Connectivité FIX et HTTP pour le routage des ordres, les données de marché et le reporting." }, { title: "Marque blanche", body: "Déployez notre plateforme sous votre marque, avec un univers d'instruments et des habilitations sur mesure." }, { title: "Accompagnement dédié", body: "Table d'exécution et équipes post-négociation dans votre fuseau horaire." }] },
    brokerages: { title: "Sociétés de courtage", intro: "Élargissez votre offre grâce à une couverture multi-actifs, une exécution compétitive et un back-office évolutif.", highlights: [{ title: "Comptes omnibus et sous-comptes", body: "Des structures de comptes flexibles adaptées à vos clients finaux." }, { title: "Marque blanche", body: "Une interface de négociation prête à l'emploi, à vos couleurs." }, { title: "Accompagnement dédié", body: "Entrée en relation, table d'exécution et rapprochement." }] },
    "asset-managers": { title: "Sociétés de gestion", intro: "Exécutez vos ordres sur les places mondiales depuis un compte unique multidevises, avec un reporting et une conservation de niveau institutionnel.", highlights: [{ title: "Exécution multi-actifs", body: "Devises, matières premières, indices, actions, obligations, métaux précieux et actifs numériques." }, { title: "Tableaux de bord de portefeuille", body: "Risque, exposition et résultat en temps réel." }, { title: "Accompagnement dédié", body: "Un chargé de relation appuyé par notre table d'exécution." }] },
    "family-offices": { title: "Family offices", intro: "Un service discret et personnalisé, alliant diversification mondiale et conservation sécurisée des actifs.", highlights: [{ title: "Diversification mondiale", body: "Accès aux marchés réglementés et de gré à gré dans le monde entier." }, { title: "Conservation sécurisée", body: "Des actifs ségrégués auprès de dépositaires reconnus." }, { title: "Accompagnement dédié", body: "Un interlocuteur unique pour chacune de vos demandes." }] },
    "professional-traders": { title: "Traders professionnels", intro: "Exécution à faible latence, profondeur de marché en temps réel et outils algorithmiques conçus par des ingénieurs qui connaissent les marchés.", highlights: [{ title: "Profondeur de marché en temps réel", body: "Transparence complète du carnet d'ordres sur toutes les places." }, { title: "Exécution algorithmique", body: "Automatisez vos entrées et sorties de position grâce à des ordres fondés sur des règles." }, { title: "Contrôle des risques", body: "Dimensionnement des positions, mécanismes d'arrêt automatique et limites d'exposition en temps réel." }] },
    "individual-investors": { title: "Investisseurs particuliers", intro: "Accédez à de nouvelles classes d'actifs via un compte unique et une plateforme qui évolue avec vous.", highlights: [{ title: "Nouvelles classes d'actifs", body: "Actions, indices, métaux précieux et actifs numériques depuis un seul compte." }, { title: "Frais transparents", body: "Des frais d'exécution et de financement clairs, convenus à l'avance." }, { title: "Accompagnement dédié", body: "Un interlocuteur humain lorsque vous en avez besoin." }] },
  },
  assetClasses: [
    { label: "Marché des changes", body: "Paires majeures, secondaires et exotiques au comptant, avec une liquidité ECN de premier rang." },
    { label: "Matières premières", body: "Contrats à terme sur l'énergie, les produits agricoles et les métaux sur les principales bourses." },
    { label: "Indices boursiers", body: "Contrats à terme et CFD sur les grands indices mondiaux, avec une liquidité profonde." },
    { label: "Actions et ETF", body: "Actions et fonds indiciels cotés sur les places américaines, européennes et asiatiques." },
    { label: "Obligations", body: "Obligations d'État et d'entreprises, cotées ou négociées de gré à gré." },
    { label: "Métaux précieux", body: "Or, argent, platine et palladium, au comptant et à terme." },
    { label: "Actifs numériques", body: "Les principaux actifs numériques via des places réglementées, 24 h/24 et 7 j/7." },
  ],
  technologyFeatures: [
    { title: "Modèles d'apprentissage automatique propriétaires", body: "Des systèmes d'apprentissage adaptatifs entraînés sur plusieurs décennies de données de marché." },
    { title: "Exécution à très faible latence", body: "Serveurs hébergés à proximité des bourses, accès direct au marché et routage intelligent des ordres." },
    { title: "Gestion avancée des risques", body: "Dimensionnement automatique des positions, mécanismes d'arrêt automatique et tests de résistance." },
    { title: "Connectivité multi-places", body: "Connexions directes à plus de 50 places réglementées et fournisseurs de liquidité." },
    { title: "Agrégation de données en temps réel", body: "Des millions de points de données par seconde, normalisés et validés." },
    { title: "Sécurité de niveau bancaire", body: "Chiffrement, authentification multifacteur et modules de sécurité matériels." },
    { title: "Tableaux de bord de portefeuille", body: "Risque, exposition et résultat en temps réel." },
    { title: "Solutions en marque blanche", body: "Votre marque sur notre infrastructure, conçue pour que vous gardiez le contrôle." },
  ],
  rateCategories: [
    { title: "Commissions d'exécution", body: "Des commissions par instrument définies dans votre grille tarifaire et communiquées avant chaque opération." },
    { title: "Financement", body: "Le coût de portage au jour le jour des positions à effet de levier, défini par instrument et par devise." },
    { title: "Coûts d'emprunt de titres", body: "Les coûts d'emprunt de titres pour les positions vendeuses, communiqués avant l'exécution." },
    { title: "Données et connectivité", body: "Données de marché et connectivité API à des tarifs fixes et publiés." },
    { title: "Conservation et règlement", body: "Les frais de conservation, de règlement-livraison et de retrait figurent dans votre grille." },
    { title: "Inactivité du compte", body: "Appliqués uniquement après une longue période sans opération." },
  ],
  pages: {
    ctaBand: { title: "Là où le capital rencontre l'intelligence des machines.", body: "Échangez avec notre équipe sur l'entrée en relation, les frais et l'intégration.", cta: { label: "Nous contacter" } },
    clients: {
      metaTitle: "Clients : institutions, family offices et traders",
      metaDescription: "Pourquoi les banques, les sociétés de courtage, les sociétés de gestion, les family offices et les traders professionnels choisissent NUUK.",
      kicker: "Clients",
      title: "Nos clients",
      intro: "Des banques aux investisseurs particuliers, NUUK offre une plateforme unique, un compte unique et un interlocuteur unique.",
      whyTitle: "Pourquoi les professionnels choisissent NUUK",
      reasons: [
        { title: "Rigueur institutionnelle", body: "Une gouvernance systématique de l'exécution, des risques et du reporting." },
        { title: "La confiance des professionnels", body: "Conçu pour les institutions et les investisseurs professionnels, du DIFC au reste du monde." },
        { title: "Accès à plus de 50 places", body: "Un compte multidevises unique et toutes les grandes classes d'actifs." },
        { title: "Technologie institutionnelle", body: "Plateforme propriétaire, API FIX/HTTP et analyses fondées sur l'IA." },
        { title: "Toujours joignables", body: "Une équipe internationale et une table d'exécution dans votre fuseau horaire." },
      ],
      whoTitle: "Qui nous accompagnons",
      ctaTitle: "Engageons la conversation",
    },
    audience: { kicker: "Clients", supportTitle: "Accompagnement dédié", supportBody: "Un chargé de relation, une table d'exécution et une équipe d'ingénieurs dans votre fuseau horaire." },
    markets: {
      metaTitle: "Marchés : une couverture multi-actifs sur plus de 50 places",
      metaDescription: "Devises, matières premières, indices boursiers, actions, obligations, métaux précieux et actifs numériques depuis un compte multidevises unique.",
      kicker: "Marchés",
      title: "Marchés",
      intro: "Négociez sur les marchés les plus liquides du monde depuis un compte multidevises unique.",
      cta: { label: "Nous rejoindre" },
      kpis: [["50+", "places réglementées"], ["150+", "modèles d'IA en production"], ["<5ms", "latence moyenne d'exécution"]],
      assetsTitle: "Classes d'actifs",
      features: [
        { title: "Accès aux marchés mondiaux", body: "Un compte unique pour les places d'Amérique, d'Europe, du Moyen-Orient et d'Asie." },
        { title: "Conservation sécurisée des actifs", body: "Des actifs clients ségrégués auprès de dépositaires reconnus." },
        { title: "Marge croisée", body: "Un calcul de marge au niveau du portefeuille, toutes classes d'actifs confondues." },
        { title: "Technologie propriétaire", body: "Plateforme web, API FIX/HTTP et analyses fondées sur l'IA." },
      ],
      depositsTitle: "Compte multidevises",
      depositsBody: "Approvisionnez votre compte en USD, EUR, GBP, AED et autres grandes devises. Détenez simultanément des soldes dans plusieurs devises et réglez vos opérations sans conversion forcée.",
    },
    pricing: {
      metaTitle: "Grille tarifaire",
      metaDescription: "Des frais d'exécution, de financement, de données et de conservation clairs et convenus à l'avance.",
      kicker: "Marchés",
      title: "Grille tarifaire",
      intro: "Des frais d'exécution, de financement, de données et de conservation clairs et convenus à l'avance. Aucun coût caché.",
      cta: { label: "Demander une grille tarifaire" },
      assetsTitle: "Classes d'actifs",
      assetNote: "Commissions et financement : selon votre grille tarifaire",
      ratesTitle: "Le détail des frais",
      ctaTitle: "Demandez votre grille tarifaire",
      ctaBody: "Les clients institutionnels et professionnels reçoivent une grille personnalisée avant l'ouverture de compte.",
    },
    technology: {
      metaTitle: "Technologie de trading : plateforme, API et IA",
      metaDescription: "Plateforme web propriétaire, API FIX et HTTP, solutions en marque blanche et analyses de marché fondées sur l'IA.",
      kicker: "Technologie",
      title: "Technologie propriétaire",
      intro: "Des systèmes de niveau institutionnel conçus pour la rapidité, la fiabilité et la performance : apprentissage automatique, exécution à faible latence et contrôle des risques réunis dans une seule architecture.",
      cta: { label: "Demander une démonstration" },
      stackTitle: "Une architecture technologique de pointe",
      httpTitle: "API HTTP",
      httpBody: "Des points d'accès REST pour les données de marché, les ordres, les positions et le reporting. Idéal pour les outils de gestion de portefeuille, les tableaux de bord et les stratégies automatisées. Sans engagement minimum.",
      fixTitle: "API FIX",
      fixBody: "Des sessions FIX 4.4 à faible latence pour le routage des ordres et le drop copy, hébergées à proximité des bourses dans les grandes places financières mondiales, pour une qualité d'exécution institutionnelle.",
      aiTitle: "Une intelligence artificielle de nouvelle génération",
      ai: [
        { title: "Réseaux d'apprentissage profond", body: "Des réseaux de neurones multicouches entraînés sur des milliards de points de données, combinant LSTM, transformeurs et apprentissage par renforcement." },
        { title: "Moteur d'analyse prédictive", body: "Des modèles de prévision qui analysent le sentiment de marché, le flux d'ordres, la volatilité et les indicateurs macroéconomiques, validés en continu par rapport aux résultats réels." },
        { title: "Gouvernance des risques", body: "Des limites d'exposition en temps réel, des mécanismes d'arrêt automatique et des tests de résistance protègent le capital en permanence." },
      ],
      infraTitle: "Une infrastructure de trading mondiale",
      infraBody: "Des connexions directes à plus de 50 places réglementées et fournisseurs de liquidité, une architecture réseau redondante, une agrégation des données en temps réel et une sécurité de niveau bancaire. Des solutions en marque blanche sont proposées aux partenaires.",
      infraCta: { label: "Échanger avec nos ingénieurs" },
    },
    company: {
      metaTitle: "À propos de NUUK : une infrastructure de trading fondée sur l'IA",
      metaDescription: "NUUK est une société de trading quantitatif et d'infrastructure de trading fondée sur l'IA, dont le siège est au DIFC, à Dubaï.",
      kicker: "À propos",
      title: "Notre histoire",
      intro: "NUUK est une société de trading quantitatif et d'infrastructure de trading fondée sur l'intelligence artificielle. Nous associons des algorithmes propriétaires, des systèmes d'exécution de niveau institutionnel et un réseau mondial de places de marché pour offrir aux professionnels un accès rigoureux aux marchés mondiaux.",
      principlesTitle: "Nos principes",
      principles: [
        { title: "Rigueur", body: "Chaque décision est systématique, maîtrisée sur le plan des risques et auditable." },
        { title: "Transparence", body: "Des tarifs clairs, un reporting clair et une communication claire." },
        { title: "Ingénierie", body: "Nous concevons nous-mêmes nos plateformes, nos modèles et nos connexions." },
        { title: "Partenariat", body: "Un chargé de relation qui connaît votre activité." },
      ],
      deliverTitle: "Vous fixez le cap, nous le mettons en œuvre",
      deliverBody: "Notre infrastructure est reliée à un vaste réseau de places de marché mondiales réglementées et de fournisseurs de liquidité, permettant une exécution automatisée sur plusieurs places avec une intégrité des données garantie, une latence maîtrisée et une gouvernance systématique complète.",
      ctaTitle: "Une équipe internationale, une présence locale",
      ctaBody: "Siège au DIFC, à Dubaï ; nous accompagnons nos clients sur tous les fuseaux horaires.",
    },
    contact: {
      metaTitle: "Nous contacter",
      metaDescription: "Échangez avec notre équipe sur l'entrée en relation, les frais et l'intégration.",
      kicker: "À propos",
      title: "Nous contacter",
      intro: "Service client, suivi de compte et demandes d'information.",
      supportTitle: "Service client",
      managerTitle: "Échangez avec notre équipe à Dubaï",
      formTitle: "Suggestions et demandes",
      form: {
        name: "Nom",
        namePlaceholder: "Votre nom et prénom",
        email: "Adresse e-mail",
        emailPlaceholder: "nom@entreprise.com",
        company: "Société (facultatif)",
        companyPlaceholder: "Nom de la société",
        message: "Message",
        messagePlaceholder: "Comment pouvons-nous vous aider ?",
        submit: "Envoyer",
        note: "Votre messagerie s'ouvrira avec le message prérempli. Aucune donnée n'est conservée sur ce site.",
        errorRequired: "Veuillez renseigner votre nom, votre adresse e-mail et votre message.",
        errorEmail: "Veuillez saisir une adresse e-mail valide.",
        subject: "Demande de",
      },
      ctaBody: "Les demandes institutionnelles et professionnelles reçoivent une réponse sous un jour ouvré.",
      ctaLabel: "Nous écrire",
    },
    footer: {
      copyright: "Tous droits réservés.",
      legal1: "est une société de trading quantitatif et d'infrastructure de trading fondée sur l'intelligence artificielle, établie au Dubai International Financial Centre. Ses services s'adressent aux clients professionnels et institutionnels ; leur disponibilité dépend de votre juridiction et de la réglementation applicable.",
      legal2: "Les informations figurant sur ce site sont fournies à titre purement informatif et ne constituent ni un conseil en investissement, ni une offre ou une sollicitation d'achat ou de vente d'un quelconque instrument ou service financier.",
      risk1: "Le trading sur les marchés financiers comporte des risques importants. Investir dans les devises, les matières premières, les indices, les actions, les obligations, les métaux précieux et les actifs numériques peut entraîner des pertes supérieures au capital investi, et le trading sur marge comporte des risques supplémentaires. Les performances passées d'un modèle, d'une stratégie ou d'un système ne préjugent pas des performances futures. Assurez-vous de bien comprendre ces risques avant de recourir à un quelconque service.",
      risk2: "Les données de marché et les indicateurs système présentés sur ce site sont fournis à titre d'illustration et peuvent être différés. Seules les demandes institutionnelles sont traitées.",
      risk3: "Vérifiez que toute communication se réclamant de NUUK provient bien du domaine nuukquant.com. Tout soupçon d'usurpation de notre nom peut être signalé à",
    },
  },
};
