import type { ContentOverride } from "@/i18n";

export const fr: ContentOverride = {
  meta: {
    title: "NUUK — Infrastructure financière par l'IA",
    description:
      "Infrastructure de trading quantitatif et d'exécution conçue par l'IA pour les institutions et les investisseurs professionnels. Devises, matières premières, indices, actions et actifs numériques sur plus de 50 places.",
  },
  brand: { office: "Dubai International Financial Centre (DIFC), Dubaï, EAU" },
  ui: {
    contact: "Contact",
    getStarted: "Commencer",
    contactUs: "Nous contacter",
    learnMore: "En savoir plus",
    language: "Langue",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    home: "Accueil NUUK",
    noPosts: "Aucune publication dans cette catégorie pour le moment.",
    riskDisclosure: "Avertissement sur les risques",
  },
  nav: [
    { label: "Clients", items: [{ label: "Banques" }, { label: "Courtiers" }, { label: "Gestionnaires d'actifs" }, { label: "Family offices" }, { label: "Traders professionnels" }, { label: "Investisseurs particuliers" }] },
    { label: "Marchés", items: [{ label: "Tous les marchés" }, { label: "Devises" }, { label: "Matières premières" }, { label: "Indices boursiers" }, { label: "Actions et ETF" }, { label: "Obligations" }, { label: "Métaux" }, { label: "Actifs numériques" }, { label: "Grille tarifaire" }] },
    { label: "Technologie", items: [{ label: "Plateforme" }, { label: "Intégration API" }, { label: "Intelligence artificielle" }, { label: "Infrastructure" }] },
    { label: "Analyses", items: [{ label: "Analyses de marché" }, { label: "Presse" }, { label: "Événements" }] },
    { label: "À propos", items: [{ label: "Notre histoire" }, { label: "Nous contacter" }, { label: "Carrières" }] },
  ],
  legalLinks: [{ label: "Avertissement sur les risques" }, { label: "Confidentialité" }, { label: "Conditions d'utilisation" }, { label: "Cookies" }, { label: "Grille tarifaire" }],
  home: {
    hero: {
      title: ["Précision.", "Intelligence.", "Exécution."],
      kicker: "INFRASTRUCTURE DE TRADING CONÇUE PAR L'IA",
      body: "NUUK est une société de trading quantitatif conçue par l'IA, active sur les marchés financiers mondiaux. Nous développons des algorithmes propriétaires, des modèles d'apprentissage automatique et des systèmes d'exécution institutionnels pour un trading discipliné et maîtrisé sur les devises, matières premières, indices, actions et actifs numériques.",
      cta: { label: "Nous contacter" },
    },
    audiences: [{ label: "Banques" }, { label: "Courtiers" }, { label: "Gestionnaires d'actifs" }, { label: "Family offices" }, { label: "Traders professionnels" }, { label: "Investisseurs particuliers" }],
    core: [
      { title: ["Couverture", "multi-actifs"], body: "Devises, matières premières, indices, actions, obligations, métaux et actifs numériques via un réseau diversifié de places réglementées et de fournisseurs de liquidité." },
      { title: ["Technologie", "propriétaire"], body: "Modèles d'apprentissage automatique développés en interne, exécution à très faible latence et plateforme web avec accès API FIX et HTTP." },
      { title: ["Grille tarifaire", "transparente"], body: "Frais d'exécution, de financement et de données clairs, convenus à l'avance. Aucune marge cachée." },
      { title: ["Service", "institutionnel"], body: "Un chargé de relation dédié, soutenu par notre desk d'exécution, notre équipe risque et nos ingénieurs." },
    ],
    servicing: {
      title: "Une seule équipe au service des institutions et des investisseurs professionnels dans le monde",
      items: ["Onboarding structuré avec accès à la plateforme et aux outils API dès le premier jour", "Couverture de tous les fuseaux horaires depuis notre base au DIFC, Dubaï", "Support du desk d'exécution pour les ordres en bloc, OTC et multi-places", "Reporting post-trade, rapprochement et analyse des risques"],
      cta: { label: "Commencer" },
    },
    network: { title: "Notre réseau", partners: ["ECN FX de premier rang", "Bourses mondiales de futures", "Places d'indices boursiers", "Places d'actifs numériques", "Dépositaires prime", "Fournisseurs de liquidité"] },
    experts: {
      title: "Plateforme de trading propriétaire",
      items: [
        { title: "Conçue par des ingénieurs", body: "Une plateforme web et un moteur d'exécution conçus en interne, accessibles via un compte unique multidevises." },
        { title: "Personnalisation et intégrations", body: "API FIX et HTTP, jeux d'instruments sur mesure et déploiements en marque blanche pour les partenaires disposant de leur propre interface." },
        { title: "Infrastructure distribuée", body: "Infrastructure colocalisée et redondante dans les principaux hubs de trading, avec une latence interne inférieure à la milliseconde." },
      ],
      cta: { label: "En savoir plus" },
      imageAlt: "Plateforme de trading NUUK sur ordinateur, portable et téléphone",
    },
    exchanges: {
      title: "Couverture mondiale des places",
      groups: [
        [{ city: "New York, États-Unis" }, { city: "Chicago, États-Unis" }, { city: "Atlanta, États-Unis" }],
        [{ city: "Londres, Royaume-Uni" }, { city: "Francfort, Allemagne" }, { city: "Zurich, Suisse" }],
        [{ city: "Dubaï, EAU" }, { city: "Abou Dabi, EAU" }],
        [{ city: "Hong Kong" }, { city: "Singapour" }, { city: "Tokyo, Japon" }],
      ],
    },
    broker: {
      title: "Fondé sur la gouvernance",
      body: "Notre infrastructure est connectée à un réseau diversifié de places réglementées, de dépositaires et de fournisseurs de liquidité, permettant une exécution automatisée multi-places avec intégrité des données, efficacité de latence et gouvernance systématique complète.",
      cta: { label: "À propos de NUUK" },
      items: [
        { title: "Gouvernance systématique", body: "Chaque décision est fondée sur des règles, journalisée et auditable." },
        { title: "Contreparties de confiance", body: "Uniquement des places réglementées et des fournisseurs de liquidité établis." },
        { title: "Conservation sécurisée", body: "Actifs des clients détenus auprès de dépositaires établis." },
        { title: "Actifs ségrégués", body: "Actifs des clients séparés des fonds de la société." },
      ],
    },
    pulse: {
      title: "Analyses NUUK",
      tabs: ["Toutes", "Analyses", "Presse", "Événements"],
      posts: [
        { title: "Taux, croissance et dollar en fin d'année", excerpt: "Ce que nos modèles macro intègrent sur les devises et les taux alors que la trajectoire de politique monétaire est réévaluée.", tag: "Analyse", date: "4 sept. 2026" },
        { title: "L'or près de ses records : ce que voit le moteur de signaux", excerpt: "Les métaux restent demandés tandis que les rendements réels se détendent. Regard sur nos signaux de momentum et de retour à la moyenne.", tag: "Analyse", date: "3 sept. 2026" },
        { title: "NUUK étend sa connectivité multi-places", excerpt: "De nouvelles connexions directes ajoutent de la profondeur sur les places de devises, de futures et d'actifs numériques.", tag: "Presse", date: "2 sept. 2026" },
        { title: "Tables rondes institutionnelles au DIFC cet automne", excerpt: "Rejoignez notre équipe pour une série de sessions à huis clos sur l'IA dans l'exécution et le risque.", tag: "Événement", date: "1 sept. 2026" },
      ],
    },
  },
  audiences: {
    banks: { title: "Banques", intro: "Exécution, connectivité et analyses pilotées par l'IA pour les banques qui ont besoin d'un accès multi-actifs via une contrepartie unique et disciplinée.", highlights: [{ title: "API directe", body: "Connectivité FIX et HTTP pour le routage d'ordres, les données de marché et le reporting." }, { title: "Marque blanche", body: "Déployez notre plateforme sous votre marque avec instruments et droits sur mesure." }, { title: "Support dédié", body: "Desk d'exécution et équipes post-trade dans votre fuseau horaire." }] },
    brokerages: { title: "Courtiers", intro: "Élargissez votre offre avec une couverture multi-actifs, une exécution compétitive et un back-office évolutif.", highlights: [{ title: "Comptes omnibus et sous-comptes", body: "Structures de comptes flexibles pour vos clients finaux." }, { title: "Marque blanche", body: "Une interface de trading prête à l'emploi à votre marque." }, { title: "Support dédié", body: "Onboarding, desk d'exécution et rapprochement." }] },
    "asset-managers": { title: "Gestionnaires d'actifs", intro: "Exécutez sur les places mondiales depuis un compte multidevises unique avec reporting et conservation institutionnels.", highlights: [{ title: "Exécution multi-actifs", body: "Devises, matières premières, indices, actions, obligations, métaux et actifs numériques." }, { title: "Tableaux de bord", body: "Risque, exposition et P&L en temps réel." }, { title: "Support dédié", body: "Un chargé de relation soutenu par notre desk d'exécution." }] },
    "family-offices": { title: "Family offices", intro: "Un service discret et personnalisé avec diversification mondiale et conservation sécurisée.", highlights: [{ title: "Diversification mondiale", body: "Accès aux marchés cotés et OTC dans le monde entier." }, { title: "Conservation sécurisée", body: "Actifs ségrégués auprès de dépositaires établis." }, { title: "Support dédié", body: "Un interlocuteur unique pour chaque demande." }] },
    "professional-traders": { title: "Traders professionnels", intro: "Exécution à faible latence, profondeur de marché en direct et outils algorithmiques conçus par des ingénieurs qui tradent.", highlights: [{ title: "Profondeur de marché en direct", body: "Transparence complète du carnet d'ordres sur toutes les places." }, { title: "Exécution algorithmique", body: "Automatisez entrées et sorties avec des ordres à règles." }, { title: "Contrôles du risque", body: "Dimensionnement des positions, coupe-circuits et limites d'exposition en temps réel." }] },
    "individual-investors": { title: "Investisseurs particuliers", intro: "Accédez à de nouvelles classes d'actifs via un seul compte et une plateforme qui grandit avec vous.", highlights: [{ title: "Nouvelles classes d'actifs", body: "Actions, indices, métaux et actifs numériques depuis un seul compte." }, { title: "Frais transparents", body: "Frais d'exécution et de financement clairs, convenus à l'avance." }, { title: "Support dédié", body: "Un support humain quand vous en avez besoin." }] },
  },
  assetClasses: [
    { label: "Devises", body: "FX spot majeures, mineures et exotiques avec liquidité ECN de premier rang." },
    { label: "Matières premières", body: "Futures sur énergie, agriculture et métaux sur les grandes bourses." },
    { label: "Indices boursiers", body: "Futures et CFD sur indices mondiaux à liquidité profonde." },
    { label: "Actions et ETF", body: "Actions et ETF cotés sur les places américaines, européennes et asiatiques." },
    { label: "Obligations", body: "Obligations d'État et d'entreprise, cotées et OTC." },
    { label: "Métaux", body: "Or, argent, platine et palladium, spot et futures." },
    { label: "Actifs numériques", body: "Principaux actifs numériques via des places réglementées, 24h/24 et 7j/7." },
  ],
  technologyFeatures: [
    { title: "Modèles ML propriétaires", body: "Systèmes d'apprentissage adaptatifs entraînés sur des décennies de données de marché." },
    { title: "Exécution à très faible latence", body: "Serveurs colocalisés, accès direct au marché et routage intelligent des ordres." },
    { title: "Gestion avancée du risque", body: "Dimensionnement automatique des positions, coupe-circuits et tests de résistance." },
    { title: "Connectivité multi-places", body: "Connexions directes à plus de 50 places réglementées et fournisseurs de liquidité." },
    { title: "Agrégation de données en temps réel", body: "Des millions de points de données par seconde, normalisés et validés." },
    { title: "Sécurité de niveau bancaire", body: "Chiffrement, authentification multifacteur et modules de sécurité matériels." },
    { title: "Tableaux de bord", body: "Risque, exposition et P&L en temps réel." },
    { title: "Solutions en marque blanche", body: "Votre marque sur notre infrastructure, conçue pour le contrôle." },
  ],
  rateCategories: [
    { title: "Commissions d'exécution", body: "Commissions par instrument convenues dans votre grille, communiquées avant chaque opération." },
    { title: "Financement", body: "Financement overnight des positions à effet de levier, par instrument et devise." },
    { title: "Coûts d'emprunt", body: "Coûts d'emprunt de titres et d'actifs pour les positions courtes, communiqués avant exécution." },
    { title: "Données et connectivité", body: "Données de marché et connectivité API à tarifs fixes publiés." },
    { title: "Conservation et règlement", body: "Frais de conservation, de règlement et de retrait listés dans votre grille." },
    { title: "Inactivité", body: "Appliqué uniquement après une longue période sans activité." },
  ],
  pages: {
    ctaBand: { title: "Là où le capital rencontre l'intelligence des machines.", body: "Parlez à notre équipe de l'onboarding, des frais et de l'intégration.", cta: { label: "Nous contacter" } },
    clients: {
      metaTitle: "Clients : institutions, family offices et traders",
      metaDescription: "Pourquoi banques, courtiers, gestionnaires d'actifs, family offices et traders professionnels choisissent NUUK.",
      kicker: "Clients",
      title: "Nos clients",
      intro: "Des banques aux investisseurs particuliers, NUUK offre une plateforme, un compte et un interlocuteur uniques.",
      whyTitle: "Pourquoi les professionnels choisissent NUUK",
      reasons: [
        { title: "Discipline institutionnelle", body: "Gouvernance systématique de l'exécution, du risque et du reporting." },
        { title: "La confiance des professionnels", body: "Conçu pour les institutions et les investisseurs professionnels, du DIFC au monde entier." },
        { title: "Accès à plus de 50 places", body: "Un compte multidevises, toutes les grandes classes d'actifs." },
        { title: "Technologie institutionnelle", body: "Plateforme propriétaire, API FIX/HTTP et analyses pilotées par l'IA." },
        { title: "Toujours disponibles", body: "Une équipe mondiale et un desk d'exécution dans votre fuseau horaire." },
      ],
      whoTitle: "Qui nous servons",
      ctaTitle: "Engagez la bonne conversation",
    },
    audience: { kicker: "Clients", supportTitle: "Support dédié", supportBody: "Un chargé de relation, un desk d'exécution et une équipe d'ingénieurs dans votre fuseau horaire." },
    markets: {
      metaTitle: "Marchés : couverture multi-actifs sur plus de 50 places",
      metaDescription: "Devises, matières premières, indices, actions, obligations, métaux et actifs numériques depuis un compte multidevises unique.",
      kicker: "Marchés",
      title: "Marchés",
      intro: "Tradez les marchés les plus liquides du monde depuis un compte multidevises unique.",
      cta: { label: "Commencer" },
      kpis: [["50+", "places réglementées"], ["150+", "modèles d'IA actifs"], ["<5ms", "latence moyenne d'exécution"]],
      assetsTitle: "Classes d'actifs",
      features: [
        { title: "Accès mondial aux places", body: "Un compte pour les places des Amériques, d'Europe, du Moyen-Orient et d'Asie." },
        { title: "Conservation sécurisée", body: "Actifs des clients ségrégués auprès de dépositaires établis." },
        { title: "Marge croisée", body: "Marge au niveau du portefeuille entre classes d'actifs." },
        { title: "Technologie propriétaire", body: "Plateforme web, API FIX/HTTP et analyses pilotées par l'IA." },
      ],
      depositsTitle: "Dépôts multidevises",
      depositsBody: "Alimentez votre compte en USD, EUR, GBP, AED et autres grandes devises. Détenez des soldes dans plusieurs devises simultanément et réglez vos opérations sans conversion forcée.",
    },
    pricing: {
      metaTitle: "Grille tarifaire",
      metaDescription: "Frais d'exécution, de financement, de données et de conservation clairs, convenus à l'avance.",
      kicker: "Marchés",
      title: "Grille tarifaire",
      intro: "Frais d'exécution, de financement, de données et de conservation clairs, convenus à l'avance. Aucune marge cachée.",
      cta: { label: "Demander une grille" },
      assetsTitle: "Classes d'actifs",
      assetNote: "Commission et financement : selon votre grille tarifaire",
      ratesTitle: "Ce que vous payez",
      ctaTitle: "Demandez votre grille tarifaire",
      ctaBody: "Les clients institutionnels et professionnels reçoivent une grille sur mesure avant l'onboarding.",
    },
    technology: {
      metaTitle: "Technologie de trading : plateforme, API et IA",
      metaDescription: "Plateforme web propriétaire, API FIX et HTTP, marque blanche et intelligence de marché pilotée par l'IA.",
      kicker: "Technologie",
      title: "Technologie propriétaire",
      intro: "Des systèmes de niveau entreprise conçus pour la vitesse, la fiabilité et la performance : apprentissage automatique, exécution à faible latence et contrôle du risque dans une seule pile.",
      cta: { label: "Demander une démo" },
      stackTitle: "Pile technologique avancée",
      httpTitle: "API HTTP",
      httpBody: "Points d'accès REST pour les données de marché, les ordres, les positions et le reporting. Idéal pour les outils de portefeuille, les tableaux de bord et les stratégies automatisées. Sans engagement minimum.",
      fixTitle: "API FIX",
      fixBody: "Sessions FIX 4.4 à faible latence pour le routage d'ordres et le drop-copy, colocalisées dans les hubs de trading mondiaux pour une qualité d'exécution institutionnelle.",
      aiTitle: "Intelligence artificielle de nouvelle génération",
      ai: [
        { title: "Réseaux d'apprentissage profond", body: "Réseaux de neurones multicouches entraînés sur des milliards de points de données, combinant LSTM, transformeurs et apprentissage par renforcement." },
        { title: "Moteur d'analyse prédictive", body: "Modèles de prévision analysant le sentiment, le flux d'ordres, la volatilité et les indicateurs macro, validés en continu sur des résultats réels." },
        { title: "Gouvernance du risque", body: "Limites d'exposition en temps réel, coupe-circuits et tests de résistance protègent le capital en permanence." },
      ],
      infraTitle: "Infrastructure de trading mondiale",
      infraBody: "Connexions directes à plus de 50 places réglementées et fournisseurs de liquidité, avec architecture réseau redondante, agrégation de données en temps réel et sécurité de niveau bancaire. Déploiements en marque blanche disponibles pour les partenaires.",
      infraCta: { label: "Parler à nos ingénieurs" },
    },
    company: {
      metaTitle: "À propos de NUUK : infrastructure de trading conçue par l'IA",
      metaDescription: "NUUK est une société de trading quantitatif et d'infrastructure conçue par l'IA, basée au DIFC à Dubaï.",
      kicker: "À propos",
      title: "Notre histoire",
      intro: "NUUK est une société de trading quantitatif et d'infrastructure conçue par l'IA. Nous combinons algorithmes propriétaires, systèmes d'exécution institutionnels et réseau mondial de places pour offrir aux professionnels un accès discipliné aux marchés mondiaux.",
      principlesTitle: "Nos principes",
      principles: [
        { title: "Discipline", body: "Chaque décision est systématique, maîtrisée en risque et auditable." },
        { title: "Transparence", body: "Des prix clairs, un reporting clair et une communication claire." },
        { title: "Ingénierie", body: "Nous construisons nous-mêmes nos plateformes, modèles et connectivités." },
        { title: "Partenariat", body: "Un chargé de relation qui connaît votre activité." },
      ],
      deliverTitle: "Vous impulsez le changement, nous le réalisons",
      deliverBody: "Notre infrastructure est connectée à un réseau diversifié de places mondiales réglementées et de fournisseurs de liquidité, permettant une exécution automatisée multi-places avec intégrité des données, efficacité de latence et gouvernance systématique complète.",
      ctaTitle: "Équipe internationale, présence locale",
      ctaBody: "Basés au DIFC à Dubaï, nous servons nos clients sur tous les fuseaux horaires.",
    },
    contact: {
      metaTitle: "Nous contacter",
      metaDescription: "Parlez à notre équipe de l'onboarding, des frais et de l'intégration.",
      kicker: "À propos",
      title: "Nous contacter",
      intro: "Support client, gestion de compte et demandes.",
      supportTitle: "Support client",
      managerTitle: "Parlez à notre équipe à Dubaï",
      formTitle: "Suggestions et demandes",
      form: {
        name: "Nom",
        namePlaceholder: "Votre nom",
        email: "E-mail",
        emailPlaceholder: "vous@entreprise.com",
        company: "Société (facultatif)",
        companyPlaceholder: "Société",
        message: "Message",
        messagePlaceholder: "Comment pouvons-nous vous aider ?",
        submit: "Envoyer la demande",
        note: "Votre client de messagerie s'ouvrira avec le message prérempli. Aucune donnée n'est stockée sur ce site.",
        errorRequired: "Veuillez renseigner votre nom, votre e-mail et votre message.",
        errorEmail: "Veuillez saisir une adresse e-mail valide.",
        subject: "Demande de",
      },
      ctaBody: "Les demandes institutionnelles et professionnelles reçoivent une réponse sous un jour ouvré.",
      ctaLabel: "Nous écrire",
    },
    footer: {
      copyright: "Tous droits réservés.",
      legal1: "est une société de trading quantitatif et d'infrastructure de trading conçue par l'IA, basée au Dubai International Financial Centre. Les services s'adressent aux clients professionnels et institutionnels ; leur disponibilité dépend de votre juridiction et de la réglementation applicable.",
      legal2: "Les informations de ce site sont fournies à titre purement informatif et ne constituent ni un conseil en investissement, ni une offre ou sollicitation d'achat ou de vente d'un instrument ou service financier.",
      risk1: "Le trading comporte des risques importants. Investir dans les devises, matières premières, indices, actions, obligations, métaux et actifs numériques peut entraîner des pertes supérieures à votre investissement initial, et le trading sur marge comporte un risque supplémentaire. Les performances passées d'un modèle, d'une stratégie ou d'un système ne préjugent pas des résultats futurs. Assurez-vous de comprendre ces risques avant de recourir à un service.",
      risk2: "Les données de marché et la télémétrie affichées sur ce site sont illustratives et peuvent être différées. Demandes institutionnelles uniquement.",
      risk3: "Vérifiez que toute communication se réclamant de NUUK provient du domaine nuukquant.com. Signalez toute utilisation abusive présumée de notre nom à",
    },
  },
};
