import type { ContentOverride } from "@/i18n";

export const tr: ContentOverride = {
  meta: {
    title: "NUUK — Finansal Yapay Zekâ Altyapısı",
    description:
      "Kurumlar ve profesyonel yatırımcılar için yapay zekâ ile tasarlanmış kantitatif işlem ve icra altyapısı. 50'den fazla piyasada döviz, emtia, endeks, hisse ve dijital varlıklar.",
  },
  brand: { office: "Dubai Uluslararası Finans Merkezi (DIFC), Dubai, BAE" },
  ui: {
    contact: "İletişim",
    getStarted: "Başlayın",
    contactUs: "Bize Ulaşın",
    learnMore: "Daha Fazla",
    language: "Dil",
    openMenu: "Menüyü aç",
    closeMenu: "Menüyü kapat",
    home: "NUUK ana sayfa",
    noPosts: "Bu kategoride henüz içerik yok.",
    riskDisclosure: "Risk bildirimi",
  },
  nav: [
    {
      label: "Müşteriler",
      items: [
        { label: "Bankalar" },
        { label: "Aracı Kurumlar" },
        { label: "Varlık Yöneticileri" },
        { label: "Aile Ofisleri" },
        { label: "Profesyonel Yatırımcılar" },
        { label: "Bireysel Yatırımcılar" },
      ],
    },
    {
      label: "Piyasalar",
      items: [
        { label: "Tüm Piyasalar" },
        { label: "Döviz" },
        { label: "Emtia" },
        { label: "Hisse Endeksleri" },
        { label: "Hisse Senetleri ve ETF'ler" },
        { label: "Sabit Getirili" },
        { label: "Değerli Metaller" },
        { label: "Dijital Varlıklar" },
        { label: "Ücret Yapısı" },
      ],
    },
    {
      label: "Teknoloji",
      items: [{ label: "Platform" }, { label: "API Entegrasyonu" }, { label: "Yapay Zekâ" }, { label: "Altyapı" }],
    },
    {
      label: "Analizler",
      items: [{ label: "Piyasa Analizleri" }, { label: "Basın" }, { label: "Etkinlikler" }],
    },
    {
      label: "Hakkımızda",
      items: [{ label: "Hikâyemiz" }, { label: "Bize Ulaşın" }, { label: "Kariyer" }],
    },
  ],
  legalLinks: [{ label: "Risk Bildirimi" }, { label: "Gizlilik" }, { label: "Kullanım Koşulları" }, { label: "Çerezler" }, { label: "Ücret Yapısı" }],
  home: {
    hero: {
      title: ["Hassasiyet.", "Zekâ.", "İcra."],
      kicker: "YAPAY ZEKÂ İLE TASARLANMIŞ İŞLEM ALTYAPISI",
      body:
        "NUUK, küresel finans piyasalarında faaliyet gösteren, yapay zekâ ile tasarlanmış bir kantitatif işlem şirketidir. Döviz, emtia, endeks, hisse ve dijital varlıklarda disiplinli ve risk kontrollü işlem için özel algoritmalar, makine öğrenmesi modelleri ve kurumsal icra sistemleri geliştiriyoruz.",
      cta: { label: "Bize Ulaşın" },
    },
    audiences: [
      { label: "Bankalar" },
      { label: "Aracı Kurumlar" },
      { label: "Varlık Yöneticileri" },
      { label: "Aile Ofisleri" },
      { label: "Profesyonel Yatırımcılar" },
      { label: "Bireysel Yatırımcılar" },
    ],
    core: [
      {
        title: ["Çoklu Varlık", "Kapsamı"],
        body: "Düzenlenmiş piyasa yerleri ve likidite sağlayıcılarından oluşan geniş bir ağ üzerinden döviz, emtia, hisse endeksleri, hisse senetleri, sabit getirili, değerli metaller ve dijital varlıklar.",
      },
      {
        title: ["Özel", "Teknoloji"],
        body: "Şirket içinde geliştirilen makine öğrenmesi modelleri, ultra düşük gecikmeli icra ve FIX/HTTP API erişimli web platformu.",
      },
      {
        title: ["Şeffaf", "Ücret Yapısı"],
        body: "Baştan anlaşılan net icra, finansman ve veri ücretleri. Gizli marj yok.",
      },
      {
        title: ["Kurumsal", "Hizmet"],
        body: "İcra masası, risk ekibi ve mühendislerimizin desteklediği özel bir ilişki yöneticisi.",
      },
    ],
    servicing: {
      title: "Dünya Genelinde Kurumlara ve Profesyonel Yatırımcılara Hizmet Veren Tek Ekip",
      items: [
        "İlk günden platform ve API araçlarına erişimle yapılandırılmış onboarding",
        "Dubai DIFC merkezimizden tüm saat dilimlerine kapsama",
        "Blok, OTC ve çoklu piyasa emirleri için icra masası desteği",
        "İşlem sonrası raporlama, mutabakat ve risk analitiği",
      ],
      cta: { label: "Başlayın" },
    },
    network: {
      title: "Ağımız",
      partners: ["1. Kademe FX ECN'leri", "Küresel Vadeli İşlem Borsaları", "Hisse Endeksi Piyasaları", "Dijital Varlık Piyasaları", "Prime Saklama Kuruluşları", "Likidite Sağlayıcılar"],
    },
    experts: {
      title: "Özel İşlem Platformu",
      items: [
        { title: "Mühendisler Tarafından Geliştirildi", body: "Şirket içinde tasarlanan web platformu ve icra motoru, tek bir çok para birimli hesap üzerinden sunulur." },
        { title: "Özelleştirme ve Entegrasyonlar", body: "FIX ve HTTP API'ler, özel enstrüman setleri ve kendi arayüzünü isteyen ortaklar için white-label kurulumlar." },
        { title: "Dağıtık Altyapı", body: "Başlıca işlem merkezlerinde eş-konumlu, yedekli altyapı ve milisaniyenin altında iç gecikme." },
      ],
      cta: { label: "Daha Fazla" },
      imageAlt: "Masaüstü, dizüstü ve telefonda NUUK işlem platformu",
    },
    exchanges: {
      title: "Küresel Piyasa Kapsamı",
      groups: [
        [{ city: "New York, ABD" }, { city: "Chicago, ABD" }, { city: "Atlanta, ABD" }],
        [{ city: "Londra, Birleşik Krallık" }, { city: "Frankfurt, Almanya" }, { city: "Zürih, İsviçre" }],
        [{ city: "Dubai, BAE" }, { city: "Abu Dabi, BAE" }],
        [{ city: "Hong Kong" }, { city: "Singapur" }, { city: "Tokyo, Japonya" }],
      ],
    },
    broker: {
      title: "Yönetişim Üzerine Kurulu",
      body:
        "Altyapımız, düzenlenmiş piyasa yerleri, saklama kuruluşları ve likidite sağlayıcılarından oluşan geniş bir ağa bağlanır; veri bütünlüğü, gecikme verimliliği ve tam sistematik yönetişimle otomatik, çoklu piyasa icrası sağlar.",
      cta: { label: "NUUK Hakkında" },
      items: [
        { title: "Sistematik Yönetişim", body: "Her karar kural tabanlı, kayıtlı ve denetlenebilir." },
        { title: "Güvenilir Karşı Taraflar", body: "Yalnızca düzenlenmiş piyasa yerleri ve yerleşik likidite sağlayıcılar." },
        { title: "Güvenli Saklama", body: "Müşteri varlıkları yerleşik saklama kuruluşlarında tutulur." },
        { title: "Ayrıştırılmış Varlıklar", body: "Müşteri varlıkları şirket fonlarından ayrı tutulur." },
      ],
    },
    pulse: {
      title: "NUUK Analizleri",
      tabs: ["Tümü", "Analizler", "Basın", "Etkinlikler"],
      posts: [
        { title: "Yıl sonuna doğru faizler, büyüme ve dolar", excerpt: "Politika patikası yeniden fiyatlanırken makro modellerimizin döviz ve faizlerde fiyatladıkları.", tag: "Analiz", date: "4 Eyl 2026" },
        { title: "Rekor seviyelere yakın altın: sinyal motoru ne görüyor", excerpt: "Reel getiriler yumuşarken metaller alıcılı. Momentum ve ortalamaya dönüş sinyallerimize bakış.", tag: "Analiz", date: "3 Eyl 2026" },
        { title: "NUUK çoklu piyasa bağlantısını genişletiyor", excerpt: "Yeni doğrudan bağlantılar döviz, vadeli işlem ve dijital varlık piyasalarında derinlik ekliyor.", tag: "Basın", date: "2 Eyl 2026" },
        { title: "Bu sonbahar DIFC'de kurumsal yuvarlak masalar", excerpt: "İcra ve riskte yapay zekâ üzerine kapalı oturumlar için ekibimize katılın.", tag: "Etkinlik", date: "1 Eyl 2026" },
      ],
    },
  },
  audiences: {
    banks: {
      title: "Bankalar",
      intro: "Tek ve disiplinli bir karşı taraf üzerinden çoklu varlık piyasa erişimine ihtiyaç duyan bankalar için icra, bağlantı ve yapay zekâ destekli analitik.",
      highlights: [
        { title: "Doğrudan API", body: "Emir yönlendirme, piyasa verisi ve raporlama için FIX ve HTTP bağlantısı." },
        { title: "White Label", body: "Platformumuzu özel enstrümanlar ve yetkilerle kendi markanız altında sunun." },
        { title: "Özel Destek", body: "Saat diliminizde icra masası ve işlem sonrası ekipleri." },
      ],
    },
    brokerages: {
      title: "Aracı Kurumlar",
      intro: "Çoklu varlık kapsamı, rekabetçi icra ve ölçeklenebilir arka ofis ile ürün yelpazenizi genişletin.",
      highlights: [
        { title: "Omnibus ve Alt Hesaplar", body: "Son müşteri yapıları için esnek hesap düzenleri." },
        { title: "White Label", body: "Markanızı taşıyan hazır bir işlem arayüzü." },
        { title: "Özel Destek", body: "Onboarding, icra masası ve mutabakat desteği." },
      ],
    },
    "asset-managers": {
      title: "Varlık Yöneticileri",
      intro: "Kurumsal raporlama ve saklama ile tek bir çok para birimli hesaptan küresel piyasalarda işlem yapın.",
      highlights: [
        { title: "Çoklu Varlık İcrası", body: "Döviz, emtia, endeks, hisse, sabit getirili, metal ve dijital varlıklar." },
        { title: "Portföy Panelleri", body: "Gerçek zamanlı risk, pozisyon ve kâr/zarar analitiği." },
        { title: "Özel Destek", body: "İcra masamızın desteklediği bir ilişki yöneticisi." },
      ],
    },
    "family-offices": {
      title: "Aile Ofisleri",
      intro: "Küresel çeşitlendirme ve güvenli saklama ile gizli, kişiye özel hizmet.",
      highlights: [
        { title: "Küresel Çeşitlendirme", body: "Dünya genelinde borsa ve tezgâh üstü piyasalara erişim." },
        { title: "Güvenli Saklama", body: "Yerleşik saklama kuruluşlarında ayrıştırılmış varlıklar." },
        { title: "Özel Destek", body: "Her talep için tek bir muhatap." },
      ],
    },
    "professional-traders": {
      title: "Profesyonel Yatırımcılar",
      intro: "İşlem yapan mühendislerin geliştirdiği düşük gecikmeli icra, canlı piyasa derinliği ve algoritmik araçlar.",
      highlights: [
        { title: "Canlı Piyasa Derinliği", body: "Piyasalar genelinde tam emir defteri şeffaflığı." },
        { title: "Algoritmik İcra", body: "Kural tabanlı emirlerle giriş ve çıkışları otomatikleştirin." },
        { title: "Risk Kontrolleri", body: "Pozisyon boyutlandırma, devre kesiciler ve gerçek zamanlı maruziyet limitleri." },
      ],
    },
    "individual-investors": {
      title: "Bireysel Yatırımcılar",
      intro: "Tek hesap ve sizinle büyüyen bir platform üzerinden yeni varlık sınıflarına erişin.",
      highlights: [
        { title: "Yeni Varlık Sınıfları", body: "Tek hesaptan hisse, endeks, metal ve dijital varlıklar." },
        { title: "Şeffaf Ücretler", body: "Baştan anlaşılan net icra ve finansman ücretleri." },
        { title: "Özel Destek", body: "İhtiyaç duyduğunuzda insan desteği." },
      ],
    },
  },
  assetClasses: [
    { label: "Döviz", body: "1. kademe ECN likiditesiyle spot döviz majörleri, minörleri ve egzotikler." },
    { label: "Emtia", body: "Başlıca borsalarda enerji, tarım ve metal vadeli işlemleri." },
    { label: "Hisse Endeksleri", body: "Derin likiditeli küresel endeks vadeli işlemleri ve CFD'ler." },
    { label: "Hisse Senetleri ve ETF'ler", body: "ABD, Avrupa ve Asya piyasalarında borsaya kote hisseler ve ETF'ler." },
    { label: "Sabit Getirili", body: "Borsa ve tezgâh üstü devlet ve şirket tahvilleri." },
    { label: "Değerli Metaller", body: "Altın, gümüş, platin ve paladyum; spot ve vadeli." },
    { label: "Dijital Varlıklar", body: "Düzenlenmiş piyasalar üzerinden başlıca dijital varlıklar, 7/24." },
  ],
  technologyFeatures: [
    { title: "Özel ML Modelleri", body: "Onlarca yıllık piyasa verisiyle eğitilmiş uyarlanabilir öğrenme sistemleri." },
    { title: "Ultra Düşük Gecikmeli İcra", body: "Eş-konumlu sunucular, doğrudan piyasa erişimi ve akıllı emir yönlendirme." },
    { title: "Gelişmiş Risk Yönetimi", body: "Otomatik pozisyon boyutlandırma, devre kesiciler ve stres testleri." },
    { title: "Çoklu Piyasa Bağlantısı", body: "50'den fazla düzenlenmiş piyasa yeri ve likidite sağlayıcıya doğrudan bağlantı." },
    { title: "Gerçek Zamanlı Veri Toplama", body: "Saniyede milyonlarca piyasa verisi; normalize edilmiş ve doğrulanmış." },
    { title: "Banka Düzeyinde Güvenlik", body: "Şifreleme, çok faktörlü kimlik doğrulama ve donanım güvenlik modülleri." },
    { title: "Portföy Panelleri", body: "Gerçek zamanlı risk, maruziyet ve kâr/zarar analitiği." },
    { title: "White Label Çözümler", body: "Bizim altyapımızda sizin markanız, kontrol için tasarlandı." },
  ],
  rateCategories: [
    { title: "İcra Komisyonları", body: "Ücret çizelgenizde belirlenen enstrüman bazlı komisyonlar; her işlemden önce açıklanır." },
    { title: "Finansman", body: "Kaldıraçlı pozisyonlarda gecelik finansman; enstrüman ve para birimi bazında." },
    { title: "Ödünç Maliyetleri", body: "Açığa satış pozisyonları için hisse ve varlık ödünç maliyetleri; icradan önce açıklanır." },
    { title: "Veri ve Bağlantı", body: "Sabit, yayınlanmış ücretlerle piyasa verisi ve API bağlantısı." },
    { title: "Saklama ve Takas", body: "Çizelgenizde listelenen saklama, takas ve para çekme ücretleri." },
    { title: "Hareketsizlik", body: "Yalnızca uzun süre işlem yapılmadığında uygulanır." },
  ],
  pages: {
    ctaBand: { title: "Sermayenin makine zekâsıyla buluştuğu yer.", body: "Onboarding, ücretler ve entegrasyon için ekibimizle görüşün.", cta: { label: "Bize Ulaşın" } },
    clients: {
      metaTitle: "Müşteriler: Kurumlar, Aile Ofisleri ve Yatırımcılar",
      metaDescription: "Bankalar, aracı kurumlar, varlık yöneticileri, aile ofisleri ve profesyonel yatırımcılar neden NUUK'u seçiyor.",
      kicker: "Müşteriler",
      title: "Müşterilerimiz",
      intro: "Bankalardan bireysel yatırımcılara, NUUK tek platform, tek hesap ve tek muhatap sunar.",
      whyTitle: "Profesyoneller neden NUUK'u seçiyor",
      reasons: [
        { title: "Kurumsal disiplin", body: "İcra, risk ve raporlamada sistematik yönetişim." },
        { title: "Profesyonellerin güveni", body: "DIFC'den dünyaya, kurumlar ve profesyonel yatırımcılar için tasarlandı." },
        { title: "50'den fazla piyasaya erişim", body: "Tek çok para birimli hesap, tüm başlıca varlık sınıfları." },
        { title: "Kurumsal teknoloji", body: "Özel platform, FIX/HTTP API'ler ve yapay zekâ destekli analitik." },
        { title: "Her zaman ulaşılabilir", body: "Saat diliminizde küresel ekip ve icra masası." },
      ],
      whoTitle: "Kime hizmet veriyoruz",
      ctaTitle: "Doğru görüşmeyi başlatın",
    },
    audience: { kicker: "Müşteriler", supportTitle: "Özel Destek", supportBody: "Saat diliminizde ilişki yöneticisi, icra masası ve mühendislik ekibi." },
    markets: {
      metaTitle: "Piyasalar: 50'den Fazla Piyasa Yerinde Çoklu Varlık Kapsamı",
      metaDescription: "Tek çok para birimli hesaptan döviz, emtia, hisse endeksleri, hisse senetleri, sabit getirili, metaller ve dijital varlıklar.",
      kicker: "Piyasalar",
      title: "Piyasalar",
      intro: "Dünyanın en likit piyasalarında tek bir çok para birimli hesapla işlem yapın.",
      cta: { label: "Başlayın" },
      kpis: [["50+", "düzenlenmiş piyasa yeri"], ["150+", "aktif yapay zekâ modeli"], ["<5ms", "ortalama icra gecikmesi"]],
      assetsTitle: "Varlık Sınıfları",
      features: [
        { title: "Küresel Piyasa Erişimi", body: "Amerika, Avrupa, Orta Doğu ve Asya'daki piyasalar için tek hesap." },
        { title: "Güvenli Varlık Saklama", body: "Yerleşik saklama kuruluşlarında ayrıştırılmış müşteri varlıkları." },
        { title: "Çapraz Teminat", body: "Varlık sınıfları arasında portföy düzeyinde teminat." },
        { title: "Özel Teknoloji", body: "Web platformu, FIX/HTTP API ve yapay zekâ destekli analitik." },
      ],
      depositsTitle: "Çok Para Birimli Mevduat",
      depositsBody: "Hesabınızı USD, EUR, GBP, AED ve diğer başlıca para birimleriyle fonlayın. Birden fazla para biriminde bakiye tutun ve zorunlu dönüşüm olmadan işlemlerinizi kapatın.",
    },
    pricing: {
      metaTitle: "Ücret Yapısı",
      metaDescription: "Baştan anlaşılan net icra, finansman, veri ve saklama ücretleri.",
      kicker: "Piyasalar",
      title: "Ücret Yapısı",
      intro: "Baştan anlaşılan net icra, finansman, veri ve saklama ücretleri. Gizli marj yok.",
      cta: { label: "Çizelge Talep Edin" },
      assetsTitle: "Varlık Sınıfları",
      assetNote: "Komisyon ve finansman: ücret çizelgenize göre",
      ratesTitle: "Ne İçin Ödeme Yaparsınız",
      ctaTitle: "Ücret çizelgenizi talep edin",
      ctaBody: "Kurumsal ve profesyonel müşteriler onboarding öncesinde özel bir çizelge alır.",
    },
    technology: {
      metaTitle: "İşlem Teknolojisi: Platform, API'ler ve Yapay Zekâ",
      metaDescription: "Özel web platformu, FIX ve HTTP API'ler, white label ve yapay zekâ destekli piyasa zekâsı.",
      kicker: "Teknoloji",
      title: "Özel Teknoloji",
      intro: "Hız, güvenilirlik ve performans için tasarlanmış kurumsal sistemler: tek yığında makine öğrenmesi, düşük gecikmeli icra ve risk kontrolü.",
      cta: { label: "Demo Talep Edin" },
      stackTitle: "Gelişmiş teknoloji yığını",
      httpTitle: "HTTP API",
      httpBody: "Piyasa verisi, emirler, pozisyonlar ve raporlama için REST uç noktaları. Portföy araçları, paneller ve otomatik stratejiler için ideal. Asgari taahhüt gerekmez.",
      fixTitle: "FIX API",
      fixBody: "Emir yönlendirme ve drop-copy için düşük gecikmeli FIX 4.4 oturumları; kurumsal icra kalitesi için küresel işlem merkezlerinde eş-konumlu.",
      aiTitle: "Yeni nesil yapay zekâ",
      ai: [
        { title: "Derin Öğrenme Ağları", body: "Milyarlarca veri noktasıyla eğitilmiş, LSTM, transformer ve pekiştirmeli öğrenmeyi birleştiren çok katmanlı sinir ağları." },
        { title: "Öngörücü Analitik Motoru", body: "Duygu, emir akışı, oynaklık ve makro göstergeleri analiz eden, gerçek sonuçlarla sürekli doğrulanan tahmin modelleri." },
        { title: "Risk Yönetişimi", body: "Gerçek zamanlı maruziyet limitleri, devre kesiciler ve stres testleri sermayeyi kesintisiz korur." },
      ],
      infraTitle: "Küresel İşlem Altyapısı",
      infraBody: "Yedekli ağ mimarisi, gerçek zamanlı veri toplama ve banka düzeyinde güvenlikle 50'den fazla düzenlenmiş piyasa yeri ve likidite sağlayıcıya doğrudan bağlantı. Ortaklar için white-label kurulumlar mevcuttur.",
      infraCta: { label: "Mühendislerimizle görüşün" },
    },
    company: {
      metaTitle: "NUUK Hakkında: Yapay Zekâ ile Tasarlanmış İşlem Altyapısı",
      metaDescription: "NUUK, merkezi Dubai DIFC'de bulunan, yapay zekâ ile tasarlanmış bir kantitatif işlem ve altyapı şirketidir.",
      kicker: "Hakkımızda",
      title: "Hikâyemiz",
      intro: "NUUK, yapay zekâ ile tasarlanmış bir kantitatif işlem ve altyapı şirketidir. Profesyonellere dünya piyasalarına disiplinli erişim sunmak için özel algoritmaları, kurumsal icra sistemlerini ve küresel piyasa ağını bir araya getiriyoruz.",
      principlesTitle: "Yol Gösterici İlkeler",
      principles: [
        { title: "Disiplin", body: "Her karar sistematik, risk kontrollü ve denetlenebilir." },
        { title: "Şeffaflık", body: "Net fiyatlama, net raporlama ve net iletişim." },
        { title: "Mühendislik", body: "Platformlarımızı, modellerimizi ve bağlantımızı kendimiz geliştiriyoruz." },
        { title: "Ortaklık", body: "İşinizi bilen bir ilişki yöneticisi." },
      ],
      deliverTitle: "Değişimi siz yönetin, biz teslim edelim",
      deliverBody: "Altyapımız, düzenlenmiş küresel piyasa yerleri ve likidite sağlayıcılardan oluşan geniş bir ağa bağlanarak veri bütünlüğü, gecikme verimliliği ve tam sistematik yönetişimle otomatik, çoklu piyasa icrası sağlar.",
      ctaTitle: "Uluslararası ekip, yerel varlık",
      ctaBody: "Merkezi Dubai DIFC'de; tüm saat dilimlerindeki müşterilere hizmet verir.",
    },
    contact: {
      metaTitle: "Bize Ulaşın",
      metaDescription: "Onboarding, ücretler ve entegrasyon için ekibimizle görüşün.",
      kicker: "Hakkımızda",
      title: "Bize Ulaşın",
      intro: "Müşteri desteği, hesap yönetimi ve talepler.",
      supportTitle: "Müşteri Desteği",
      managerTitle: "Dubai'deki ekibimizle görüşün",
      formTitle: "Öneri ve Talepler",
      form: {
        name: "Ad Soyad",
        namePlaceholder: "Adınız",
        email: "E-posta",
        emailPlaceholder: "siz@sirket.com",
        company: "Şirket (isteğe bağlı)",
        companyPlaceholder: "Şirket",
        message: "Mesaj",
        messagePlaceholder: "Nasıl yardımcı olabiliriz?",
        submit: "Talep gönder",
        note: "Bu işlem e-posta istemcinizi mesaj hazır hâlde açar. Bu sitede hiçbir veri saklanmaz.",
        errorRequired: "Lütfen ad, e-posta ve mesaj alanlarını doldurun.",
        errorEmail: "Lütfen geçerli bir e-posta adresi girin.",
        subject: "Talep:",
      },
      ctaBody: "Kurumsal ve profesyonel talepler bir iş günü içinde yanıtlanır.",
      ctaLabel: "E-posta gönderin",
    },
    footer: {
      copyright: "Tüm hakları saklıdır.",
      legal1: "Dubai Uluslararası Finans Merkezi'nde yerleşik, yapay zekâ ile tasarlanmış bir kantitatif işlem ve işlem altyapısı şirketidir. Hizmetler profesyonel ve kurumsal müşterilere sunulur; erişilebilirlik bulunduğunuz yargı bölgesine ve geçerli mevzuata bağlıdır.",
      legal2: "Bu web sitesindeki bilgiler yalnızca bilgilendirme amaçlıdır; yatırım tavsiyesi ya da herhangi bir finansal araç veya hizmetin alım-satımına yönelik teklif veya davet niteliği taşımaz.",
      risk1: "İşlem yapmak önemli risk içerir. Döviz, emtia, endeks, hisse, sabit getirili, metal ve dijital varlıklara yatırım, başlangıç yatırımınızı aşan kayıplara yol açabilir; kaldıraçlı işlem ek risk taşır. Herhangi bir modelin, stratejinin veya sistemin geçmiş performansı gelecekteki sonuçların garantisi değildir. Herhangi bir hizmeti kullanmadan önce bu riskleri anladığınızdan emin olun.",
      risk2: "Bu web sitesinde gösterilen canlı piyasa verileri ve sistem telemetrisi örnek amaçlıdır ve gecikmeli olabilir. Yalnızca kurumsal talepler.",
      risk3: "NUUK adına yapıldığı iddia edilen her iletişimin nuukquant.com alan adından geldiğini doğrulayın. Adımızın kötüye kullanıldığından şüpheleniyorsanız şu adrese bildirin:",
    },
  },
};
