import type { ContentOverride } from "@/i18n";

export const tr: ContentOverride = {
  meta: {
    title: "NUUK — Finansal Yapay Zekâ Altyapısı",
    description:
      "Kurumsal ve profesyonel yatırımcılar için yapay zekâ destekli kantitatif işlem ve emir gerçekleştirme altyapısı. 50'den fazla piyasada döviz, emtia, endeks, hisse senedi ve dijital varlıklar.",
  },
  brand: { office: "Dubai Uluslararası Finans Merkezi (DIFC), Dubai, BAE" },
  ui: {
    contact: "İletişim",
    getStarted: "Başvurun",
    contactUs: "Bize Ulaşın",
    learnMore: "Detaylı Bilgi",
    language: "Dil",
    openMenu: "Menüyü aç",
    closeMenu: "Menüyü kapat",
    home: "NUUK ana sayfa",
    noPosts: "Bu kategoride henüz yayın bulunmuyor.",
    riskDisclosure: "Risk bildirimi",
  },
  nav: [
    {
      label: "Müşteriler",
      items: [
        { label: "Bankalar" },
        { label: "Aracı Kurumlar" },
        { label: "Portföy Yönetim Şirketleri" },
        { label: "Aile Ofisleri" },
        { label: "Profesyonel Yatırımcılar" },
        { label: "Bireysel Yatırımcılar" },
      ],
    },
    {
      label: "Piyasalar",
      items: [
        { label: "Tüm Piyasalar" },
        { label: "Döviz" },
        { label: "Emtia" },
        { label: "Hisse Senedi Endeksleri" },
        { label: "Hisse Senetleri ve ETF'ler" },
        { label: "Sabit Getirili Menkul Kıymetler" },
        { label: "Kıymetli Madenler" },
        { label: "Dijital Varlıklar" },
        { label: "Ücret Tarifesi" },
      ],
    },
    {
      label: "Teknoloji",
      items: [{ label: "Platform" }, { label: "API Entegrasyonu" }, { label: "Yapay Zekâ" }, { label: "Altyapı" }],
    },
    {
      label: "Görüşler",
      items: [{ label: "Piyasa Görüşleri" }, { label: "Basın" }, { label: "Etkinlikler" }],
    },
    {
      label: "Hakkımızda",
      items: [{ label: "Hikâyemiz" }, { label: "Bize Ulaşın" }, { label: "Kariyer" }],
    },
  ],
  legalLinks: [{ label: "Risk Bildirimi" }, { label: "Gizlilik" }, { label: "Kullanım Koşulları" }, { label: "Çerezler" }, { label: "Ücret Tarifesi" }],
  home: {
    hero: {
      title: ["Kesinlik.", "Zekâ.", "Gerçekleştirme."],
      kicker: "YAPAY ZEKÂ DESTEKLİ İŞLEM ALTYAPISI",
      body:
        "NUUK, küresel finans piyasalarında faaliyet gösteren, yapay zekâ destekli bir kantitatif işlem şirketidir. Döviz, emtia, endeks, hisse senedi ve dijital varlık piyasalarında disiplinli ve risk kontrollü işlem yapılmasını sağlayan özel algoritmalar, makine öğrenimi modelleri ve kurumsal emir gerçekleştirme sistemleri geliştiriyoruz.",
      cta: { label: "Bize Ulaşın" },
    },
    audiences: [
      { label: "Bankalar" },
      { label: "Aracı Kurumlar" },
      { label: "Portföy Yönetim Şirketleri" },
      { label: "Aile Ofisleri" },
      { label: "Profesyonel Yatırımcılar" },
      { label: "Bireysel Yatırımcılar" },
    ],
    core: [
      {
        title: ["Çoklu Varlık", "Kapsamı"],
        body: "Düzenlemeye tabi borsalar ve likidite sağlayıcılarından oluşan geniş bir ağ üzerinden döviz, emtia, hisse senedi endeksleri, hisse senetleri, sabit getirili menkul kıymetler, kıymetli madenler ve dijital varlıklara erişim.",
      },
      {
        title: ["Özel", "Teknoloji"],
        body: "Şirket bünyesinde geliştirilen makine öğrenimi modelleri, çok düşük gecikmeli emir gerçekleştirme ve FIX/HTTP API erişimi sunan web platformu.",
      },
      {
        title: ["Şeffaf", "Ücret Tarifesi"],
        body: "Baştan belirlenen net işlem, finansman ve veri ücretleri. Gizli maliyet yok.",
      },
      {
        title: ["Kurumsal", "Hizmet"],
        body: "İşlem masası, risk ekibi ve mühendislerimizin desteğiyle çalışan, size özel bir müşteri ilişkileri yöneticisi.",
      },
    ],
    servicing: {
      title: "Dünya Genelinde Kurumlara ve Profesyonel Yatırımcılara Hizmet Veren Tek Bir Ekip",
      items: [
        "İlk günden platforma ve API araçlarına erişimle planlı hesap açılışı",
        "Dubai DIFC'deki merkezimizden tüm zaman dilimlerine hizmet",
        "Blok, tezgâh üstü ve çoklu piyasa emirleri için işlem masası desteği",
        "İşlem sonrası raporlama, mutabakat ve risk analitiği",
      ],
      cta: { label: "Başvurun" },
    },
    network: {
      title: "İş Ortağı Ağımız",
      partners: ["Birinci Kademe FX ECN Ağları", "Küresel Vadeli İşlem Borsaları", "Endeks İşlem Platformları", "Dijital Varlık Platformları", "Ana Saklama Kuruluşları", "Likidite Sağlayıcılar"],
    },
    experts: {
      title: "Özel İşlem Platformu",
      items: [
        { title: "Mühendislerimiz Tarafından Geliştirildi", body: "Şirket bünyesinde tasarlanan web platformu ve emir gerçekleştirme motoru, tek bir çok para birimli hesap üzerinden sunulur." },
        { title: "Özelleştirme ve Entegrasyonlar", body: "FIX ve HTTP API'ler, özel enstrüman setleri ve kendi arayüzünü kullanmak isteyen iş ortakları için beyaz etiket (white label) çözümleri." },
        { title: "Dağıtık Altyapı", body: "Başlıca finans merkezlerinde borsalara yakın konumlandırılmış, yedekli altyapı ve bir milisaniyenin altında iç gecikme süresi." },
      ],
      cta: { label: "Detaylı Bilgi" },
      imageAlt: "Masaüstü, dizüstü bilgisayar ve telefonda NUUK işlem platformu",
    },
    exchanges: {
      title: "Küresel Piyasa Erişimi",
      groups: [
        [{ city: "New York, ABD" }, { city: "Chicago, ABD" }, { city: "Atlanta, ABD" }],
        [{ city: "Londra, Birleşik Krallık" }, { city: "Frankfurt, Almanya" }, { city: "Zürih, İsviçre" }],
        [{ city: "Dubai, BAE" }, { city: "Abu Dabi, BAE" }],
        [{ city: "Hong Kong" }, { city: "Singapur" }, { city: "Tokyo, Japonya" }],
      ],
    },
    broker: {
      title: "Kurumsal Yönetişim Temelinde",
      body:
        "Altyapımız, düzenlemeye tabi borsalar, saklama kuruluşları ve likidite sağlayıcılarından oluşan geniş bir ağa bağlıdır. Bu sayede veri bütünlüğü, düşük gecikme ve eksiksiz sistematik denetimle çoklu piyasada otomatik emir gerçekleştirme sunar.",
      cta: { label: "NUUK Hakkında" },
      items: [
        { title: "Sistematik Yönetişim", body: "Her karar kurallara dayanır, kayıt altına alınır ve denetlenebilir." },
        { title: "Güvenilir Karşı Taraflar", body: "Yalnızca düzenlemeye tabi borsalar ve köklü likidite sağlayıcılar." },
        { title: "Güvenli Saklama", body: "Müşteri varlıkları köklü saklama kuruluşlarında tutulur." },
        { title: "Ayrıştırılmış Varlıklar", body: "Müşteri varlıkları şirket varlıklarından ayrı hesaplarda tutulur." },
      ],
    },
    pulse: {
      title: "NUUK Görüşleri",
      tabs: ["Tüm Yayınlar", "Görüşler", "Basın", "Etkinlikler"],
      posts: [
        { title: "Yıl sonuna doğru faizler, büyüme ve dolar", excerpt: "Para politikası patikası yeniden fiyatlanırken makro modellerimizin döviz ve faiz piyasalarına ilişkin öngörüleri.", tag: "Görüş", date: "4 Eylül 2026" },
        { title: "Rekor seviyelere yakın altın: sinyal motorumuzun okuması", excerpt: "Reel getiriler gevşerken kıymetli madenlerde alım ilgisi sürüyor. Momentum ve ortalamaya dönüş sinyallerimize bakış.", tag: "Görüş", date: "3 Eylül 2026" },
        { title: "NUUK çoklu piyasa bağlantısını genişletiyor", excerpt: "Yeni doğrudan bağlantılar döviz, vadeli işlem ve dijital varlık piyasalarında derinliği artırıyor.", tag: "Basın", date: "2 Eylül 2026" },
        { title: "Bu sonbahar DIFC'de kurumsal yuvarlak masa toplantıları", excerpt: "Emir gerçekleştirme ve risk yönetiminde yapay zekâ konulu kapalı oturumlarımıza davetlisiniz.", tag: "Etkinlik", date: "1 Eylül 2026" },
      ],
    },
  },
  audiences: {
    banks: {
      title: "Bankalar",
      intro: "Tek ve disiplinli bir karşı taraf üzerinden çoklu varlık sınıfında piyasa erişimine ihtiyaç duyan bankalar için emir gerçekleştirme, bağlantı ve yapay zekâ destekli analitik hizmetleri.",
      highlights: [
        { title: "Doğrudan API", body: "Emir iletimi, piyasa verisi ve raporlama için FIX ve HTTP bağlantısı." },
        { title: "Beyaz Etiket", body: "Platformumuzu size özel enstrümanlar ve yetkilendirmelerle kendi markanız altında sunun." },
        { title: "Özel Destek", body: "Zaman diliminizde hizmet veren işlem masası ve işlem sonrası ekipleri." },
      ],
    },
    brokerages: {
      title: "Aracı Kurumlar",
      intro: "Çoklu varlık kapsamı, rekabetçi emir gerçekleştirme ve ölçeklenebilir arka ofis hizmetleriyle ürün yelpazenizi genişletin.",
      highlights: [
        { title: "Toplu ve Alt Hesaplar", body: "Nihai müşteri yapılarına uygun esnek hesap düzenleri." },
        { title: "Beyaz Etiket", body: "Markanızı taşıyan, kullanıma hazır bir işlem arayüzü." },
        { title: "Özel Destek", body: "Hesap açılışı, işlem masası ve mutabakat desteği." },
      ],
    },
    "asset-managers": {
      title: "Portföy Yönetim Şirketleri",
      intro: "Kurumsal raporlama ve saklama hizmetiyle tek bir çok para birimli hesaptan küresel piyasalarda işlem yapın.",
      highlights: [
        { title: "Çoklu Varlık İşlemleri", body: "Döviz, emtia, endeks, hisse senedi, sabit getirili, kıymetli maden ve dijital varlıklar." },
        { title: "Portföy Panelleri", body: "Gerçek zamanlı risk, pozisyon ve kâr/zarar analitiği." },
        { title: "Özel Destek", body: "İşlem masamızın desteğiyle çalışan bir müşteri ilişkileri yöneticisi." },
      ],
    },
    "family-offices": {
      title: "Aile Ofisleri",
      intro: "Küresel çeşitlendirme ve güvenli saklama ile gizliliğe önem veren, kişiye özel hizmet.",
      highlights: [
        { title: "Küresel Çeşitlendirme", body: "Dünya genelinde organize borsalara ve tezgâh üstü piyasalara erişim." },
        { title: "Güvenli Saklama", body: "Köklü saklama kuruluşlarında ayrıştırılmış varlıklar." },
        { title: "Özel Destek", body: "Her talebiniz için tek bir muhatap." },
      ],
    },
    "professional-traders": {
      title: "Profesyonel Yatırımcılar",
      intro: "Piyasayı bilen mühendislerin geliştirdiği düşük gecikmeli emir gerçekleştirme, canlı piyasa derinliği ve algoritmik işlem araçları.",
      highlights: [
        { title: "Canlı Piyasa Derinliği", body: "Tüm piyasalarda tam emir defteri şeffaflığı." },
        { title: "Algoritmik İşlem", body: "Kural tabanlı emirlerle giriş ve çıkışlarınızı otomatikleştirin." },
        { title: "Risk Kontrolleri", body: "Pozisyon büyüklüğü yönetimi, otomatik durdurma mekanizmaları ve gerçek zamanlı risk limitleri." },
      ],
    },
    "individual-investors": {
      title: "Bireysel Yatırımcılar",
      intro: "Tek bir hesap ve sizinle birlikte büyüyen bir platformla yeni varlık sınıflarına erişin.",
      highlights: [
        { title: "Yeni Varlık Sınıfları", body: "Tek hesaptan hisse senedi, endeks, kıymetli maden ve dijital varlıklar." },
        { title: "Şeffaf Ücretler", body: "Baştan belirlenen net işlem ve finansman ücretleri." },
        { title: "Özel Destek", body: "İhtiyaç duyduğunuz anda gerçek bir muhatap." },
      ],
    },
  },
  assetClasses: [
    { label: "Döviz", body: "Birinci kademe ECN likiditesiyle spot piyasada ana, ikincil ve egzotik paritelerde işlem." },
    { label: "Emtia", body: "Başlıca borsalarda enerji, tarım ürünleri ve maden vadeli işlem sözleşmeleri." },
    { label: "Hisse Senedi Endeksleri", body: "Derin likiditeye sahip küresel endeks vadeli işlemleri ve fark sözleşmeleri (CFD)." },
    { label: "Hisse Senetleri ve ETF'ler", body: "ABD, Avrupa ve Asya borsalarında işlem gören hisse senetleri ve borsa yatırım fonları." },
    { label: "Sabit Getirili Menkul Kıymetler", body: "Organize ve tezgâh üstü piyasalarda devlet ve özel sektör tahvilleri." },
    { label: "Kıymetli Madenler", body: "Altın, gümüş, platin ve paladyum; spot ve vadeli işlemler." },
    { label: "Dijital Varlıklar", body: "Düzenlemeye tabi platformlar üzerinden başlıca dijital varlıklar; 7/24." },
  ],
  technologyFeatures: [
    { title: "Özel Makine Öğrenimi Modelleri", body: "On yılların piyasa verisiyle eğitilmiş, uyarlanabilir öğrenme sistemleri." },
    { title: "Çok Düşük Gecikmeli Emir Gerçekleştirme", body: "Borsalara yakın konumlandırılmış sunucular, doğrudan piyasa erişimi ve akıllı emir yönlendirme." },
    { title: "Gelişmiş Risk Yönetimi", body: "Otomatik pozisyon büyüklüğü yönetimi, otomatik durdurma mekanizmaları ve stres testleri." },
    { title: "Çoklu Piyasa Bağlantısı", body: "50'den fazla düzenlemeye tabi borsa ve likidite sağlayıcıya doğrudan bağlantı." },
    { title: "Gerçek Zamanlı Veri Toplama", body: "Saniyede milyonlarca piyasa verisi; standartlaştırılmış ve doğrulanmış." },
    { title: "Banka Düzeyinde Güvenlik", body: "Şifreleme, çok faktörlü kimlik doğrulama ve donanım güvenlik modülleri." },
    { title: "Portföy Panelleri", body: "Gerçek zamanlı risk, pozisyon ve kâr/zarar analitiği." },
    { title: "Beyaz Etiket Çözümleri", body: "Kontrolü sizde tutacak şekilde tasarlanmış altyapımız üzerinde kendi markanız." },
  ],
  rateCategories: [
    { title: "İşlem Komisyonları", body: "Ücret tarifenizde belirlenen enstrüman bazlı komisyonlar; her işlemden önce açıkça bildirilir." },
    { title: "Finansman", body: "Kaldıraçlı pozisyonlar için gecelik finansman maliyeti; enstrüman ve para birimi bazında belirlenir." },
    { title: "Ödünç Maliyetleri", body: "Açığa satış pozisyonları için menkul kıymet ödünç maliyetleri; işlemden önce bildirilir." },
    { title: "Veri ve Bağlantı", body: "Sabit ve yayımlanmış ücretlerle piyasa verisi ve API bağlantısı." },
    { title: "Saklama ve Takas", body: "Tarifenizde yer alan saklama, takas ve para çekme ücretleri." },
    { title: "Hesap Hareketsizliği", body: "Yalnızca uzun süre işlem yapılmaması hâlinde uygulanır." },
  ],
  pages: {
    ctaBand: { title: "Sermayenin makine zekâsıyla buluştuğu yer.", body: "Hesap açılışı, ücretler ve entegrasyon için ekibimizle görüşün.", cta: { label: "Bize Ulaşın" } },
    clients: {
      metaTitle: "Müşteriler: Kurumlar, Aile Ofisleri ve Yatırımcılar",
      metaDescription: "Bankalar, aracı kurumlar, portföy yönetim şirketleri, aile ofisleri ve profesyonel yatırımcılar NUUK'u neden tercih ediyor?",
      kicker: "Müşteriler",
      title: "Müşterilerimiz",
      intro: "Bankalardan bireysel yatırımcılara kadar NUUK; tek platform, tek hesap ve tek muhatap sunar.",
      whyTitle: "Profesyoneller NUUK'u neden tercih ediyor?",
      reasons: [
        { title: "Kurumsal disiplin", body: "Emir gerçekleştirme, risk ve raporlamada sistematik yönetişim." },
        { title: "Profesyonellerin güveni", body: "DIFC'den dünyaya; kurumlar ve profesyonel yatırımcılar için tasarlandı." },
        { title: "50'den fazla piyasaya erişim", body: "Tek bir çok para birimli hesap, tüm başlıca varlık sınıfları." },
        { title: "Kurumsal teknoloji", body: "Özel platform, FIX/HTTP API'ler ve yapay zekâ destekli analitik." },
        { title: "Her zaman ulaşılabilir", body: "Zaman diliminizde hizmet veren küresel ekip ve işlem masası." },
      ],
      whoTitle: "Kimlere hizmet veriyoruz?",
      ctaTitle: "Doğru görüşmeyi başlatın",
    },
    audience: { kicker: "Müşteriler", supportTitle: "Özel Destek", supportBody: "Zaman diliminizde müşteri ilişkileri yöneticisi, işlem masası ve mühendislik ekibi." },
    markets: {
      metaTitle: "Piyasalar: 50'den Fazla Piyasada Çoklu Varlık Kapsamı",
      metaDescription: "Tek bir çok para birimli hesaptan döviz, emtia, hisse senedi endeksleri, hisse senetleri, sabit getirili menkul kıymetler, kıymetli madenler ve dijital varlıklar.",
      kicker: "Piyasalar",
      title: "Piyasalar",
      intro: "Dünyanın en likit piyasalarında tek bir çok para birimli hesapla işlem yapın.",
      cta: { label: "Başvurun" },
      kpis: [["50+", "düzenlemeye tabi piyasa"], ["150+", "aktif yapay zekâ modeli"], ["<5ms", "ortalama emir gerçekleştirme süresi"]],
      assetsTitle: "Varlık Sınıfları",
      features: [
        { title: "Küresel Piyasa Erişimi", body: "Amerika, Avrupa, Orta Doğu ve Asya piyasaları için tek hesap." },
        { title: "Güvenli Varlık Saklama", body: "Köklü saklama kuruluşlarında ayrıştırılmış müşteri varlıkları." },
        { title: "Çapraz Teminatlandırma", body: "Varlık sınıfları arasında portföy bazlı teminat hesaplaması." },
        { title: "Özel Teknoloji", body: "Web platformu, FIX/HTTP API ve yapay zekâ destekli analitik." },
      ],
      depositsTitle: "Çok Para Birimli Hesap",
      depositsBody: "Hesabınıza USD, EUR, GBP, AED ve diğer başlıca para birimlerinde para yatırın. Aynı anda birden fazla para biriminde bakiye tutun; işlemlerinizi zorunlu dönüşüm olmadan takas edin.",
    },
    pricing: {
      metaTitle: "Ücret Tarifesi",
      metaDescription: "Baştan belirlenen net işlem, finansman, veri ve saklama ücretleri.",
      kicker: "Piyasalar",
      title: "Ücret Tarifesi",
      intro: "Baştan belirlenen net işlem, finansman, veri ve saklama ücretleri. Gizli maliyet yok.",
      cta: { label: "Tarife Talep Edin" },
      assetsTitle: "Varlık Sınıfları",
      assetNote: "Komisyon ve finansman: ücret tarifenize göre",
      ratesTitle: "Ücret Kalemleri",
      ctaTitle: "Ücret tarifenizi talep edin",
      ctaBody: "Kurumsal ve profesyonel müşterilere hesap açılışından önce size özel bir tarife sunulur.",
    },
    technology: {
      metaTitle: "İşlem Teknolojisi: Platform, API'ler ve Yapay Zekâ",
      metaDescription: "Özel web platformu, FIX ve HTTP API'ler, beyaz etiket çözümleri ve yapay zekâ destekli piyasa analitiği.",
      kicker: "Teknoloji",
      title: "Özel Teknoloji",
      intro: "Hız, güvenilirlik ve performans için tasarlanmış kurumsal düzeyde sistemler: makine öğrenimi, düşük gecikmeli emir gerçekleştirme ve risk kontrolü tek bir yapıda.",
      cta: { label: "Demo Talep Edin" },
      stackTitle: "Gelişmiş teknoloji altyapısı",
      httpTitle: "HTTP API",
      httpBody: "Piyasa verisi, emirler, pozisyonlar ve raporlama için REST uç noktaları. Portföy araçları, gösterge panelleri ve otomatik stratejiler için idealdir. Asgari taahhüt gerektirmez.",
      fixTitle: "FIX API",
      fixBody: "Emir iletimi ve kopya raporlama (drop copy) için düşük gecikmeli FIX 4.4 oturumları; kurumsal düzeyde gerçekleştirme kalitesi için küresel finans merkezlerinde borsalara yakın konumlandırılmıştır.",
      aiTitle: "Yeni nesil yapay zekâ",
      ai: [
        { title: "Derin Öğrenme Ağları", body: "Milyarlarca veri noktasıyla eğitilmiş; LSTM, transformer ve pekiştirmeli öğrenme yaklaşımlarını birleştiren çok katmanlı sinir ağları." },
        { title: "Öngörücü Analitik Motoru", body: "Piyasa duyarlılığı, emir akışı, oynaklık ve makroekonomik göstergeleri analiz eden, gerçek sonuçlarla sürekli doğrulanan tahmin modelleri." },
        { title: "Risk Yönetişimi", body: "Gerçek zamanlı risk limitleri, otomatik durdurma mekanizmaları ve stres testleri sermayeyi kesintisiz korur." },
      ],
      infraTitle: "Küresel İşlem Altyapısı",
      infraBody: "Yedekli ağ mimarisi, gerçek zamanlı veri toplama ve banka düzeyinde güvenlikle 50'den fazla düzenlemeye tabi borsa ve likidite sağlayıcıya doğrudan bağlantı. İş ortakları için beyaz etiket kurulumları mevcuttur.",
      infraCta: { label: "Mühendislerimizle görüşün" },
    },
    company: {
      metaTitle: "NUUK Hakkında: Yapay Zekâ Destekli İşlem Altyapısı",
      metaDescription: "NUUK, merkezi Dubai DIFC'de bulunan, yapay zekâ destekli bir kantitatif işlem ve altyapı şirketidir.",
      kicker: "Hakkımızda",
      title: "Hikâyemiz",
      intro: "NUUK, yapay zekâ destekli bir kantitatif işlem ve altyapı şirketidir. Profesyonellere dünya piyasalarına disiplinli erişim sunmak için özel algoritmaları, kurumsal emir gerçekleştirme sistemlerini ve küresel piyasa ağını bir araya getiriyoruz.",
      principlesTitle: "Temel İlkelerimiz",
      principles: [
        { title: "Disiplin", body: "Her karar sistematik, risk kontrollü ve denetlenebilirdir." },
        { title: "Şeffaflık", body: "Net fiyatlama, net raporlama ve net iletişim." },
        { title: "Mühendislik", body: "Platformlarımızı, modellerimizi ve bağlantı altyapımızı kendimiz geliştiriyoruz." },
        { title: "İş Ortaklığı", body: "İşinizi yakından tanıyan bir müşteri ilişkileri yöneticisi." },
      ],
      deliverTitle: "Yönü siz belirleyin, hayata biz geçirelim",
      deliverBody: "Altyapımız, düzenlemeye tabi küresel borsalar ve likidite sağlayıcılarından oluşan geniş bir ağa bağlıdır; veri bütünlüğü, düşük gecikme ve eksiksiz sistematik denetimle çoklu piyasada otomatik emir gerçekleştirme sunar.",
      ctaTitle: "Uluslararası ekip, yerel varlık",
      ctaBody: "Merkezimiz Dubai DIFC'de; tüm zaman dilimlerindeki müşterilerimize hizmet veriyoruz.",
    },
    contact: {
      metaTitle: "Bize Ulaşın",
      metaDescription: "Hesap açılışı, ücretler ve entegrasyon için ekibimizle görüşün.",
      kicker: "Hakkımızda",
      title: "Bize Ulaşın",
      intro: "Müşteri desteği, hesap yönetimi ve bilgi talepleri.",
      supportTitle: "Müşteri Desteği",
      managerTitle: "Dubai'deki ekibimizle görüşün",
      formTitle: "Görüş ve Talepler",
      form: {
        name: "Ad Soyad",
        namePlaceholder: "Adınız ve soyadınız",
        email: "E-posta",
        emailPlaceholder: "ad@sirket.com",
        company: "Şirket (isteğe bağlı)",
        companyPlaceholder: "Şirket adı",
        message: "Mesaj",
        messagePlaceholder: "Size nasıl yardımcı olabiliriz?",
        submit: "Gönder",
        note: "Bu işlem, mesajınız hazır hâlde e-posta uygulamanızı açar. Bu sitede hiçbir veri saklanmaz.",
        errorRequired: "Lütfen ad, e-posta ve mesaj alanlarını doldurun.",
        errorEmail: "Lütfen geçerli bir e-posta adresi girin.",
        subject: "Bilgi talebi:",
      },
      ctaBody: "Kurumsal ve profesyonel talepler bir iş günü içinde yanıtlanır.",
      ctaLabel: "E-posta gönderin",
    },
    footer: {
      copyright: "Tüm hakları saklıdır.",
      legal1: "Dubai Uluslararası Finans Merkezi'nde yerleşik, yapay zekâ destekli bir kantitatif işlem ve işlem altyapısı şirketidir. Hizmetler profesyonel ve kurumsal müşterilere sunulur; hizmetlerin sunulabilirliği bulunduğunuz ülkenin mevzuatına bağlıdır.",
      legal2: "Bu web sitesindeki bilgiler yalnızca bilgilendirme amaçlıdır; yatırım danışmanlığı ya da herhangi bir finansal araç veya hizmetin alım satımına yönelik bir teklif veya davet niteliği taşımaz.",
      risk1: "Finansal piyasalarda işlem yapmak önemli ölçüde risk içerir. Döviz, emtia, endeks, hisse senedi, sabit getirili menkul kıymet, kıymetli maden ve dijital varlık yatırımları başlangıç sermayenizi aşan zararlara yol açabilir; kaldıraçlı işlemler ek risk taşır. Herhangi bir modelin, stratejinin veya sistemin geçmiş performansı gelecekteki sonuçların göstergesi değildir. Herhangi bir hizmeti kullanmadan önce bu riskleri anladığınızdan emin olun.",
      risk2: "Bu web sitesinde gösterilen canlı piyasa verileri ve sistem göstergeleri temsilî niteliktedir ve gecikmeli olabilir. Yalnızca kurumsal talepler değerlendirilir.",
      risk3: "NUUK adına yapıldığı iddia edilen her iletişimin nuukquant.com alan adından geldiğini doğrulayın. Adımızın kötüye kullanıldığından şüpheleniyorsanız lütfen şu adrese bildirin:",
    },
  },
};
